controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
