when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
    
    framework:
        profiler:
            enabled: true

when@test:
    framework:
        profiler:
            enabled: false
