when@dev:
    web_profiler:
        toolbar: true
<<<<<<< HEAD
        intercept_redirects: false
    
    framework:
        profiler:
            enabled: true

when@test:
    framework:
        profiler:
            enabled: false
=======

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler: { collect: false }
>>>>>>> testsisi
