<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EwosNoVService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.EwosNoV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookingRepo' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
            'circuitAvisRepo' => ['privates', 'App\\Repository\\CircuitAvisRepository', 'getCircuitAvisRepositoryService', true],
            'favActRepo' => ['privates', 'App\\Repository\\FavoriteActivityRepository', 'getFavoriteActivityRepositoryService', true],
            'favCircRepo' => ['privates', 'App\\Repository\\FavoriteCircuitRepository', 'getFavoriteCircuitRepositoryService', true],
            'favHebRepo' => ['privates', 'App\\Repository\\FavoriteHebergementRepository', 'getFavoriteHebergementRepositoryService', true],
            'favPostRepo' => ['privates', 'App\\Repository\\FavoritePostRepository', 'getFavoritePostRepositoryService', true],
            'favTransRepo' => ['privates', 'App\\Repository\\FavoriteTransportRepository', 'getFavoriteTransportRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'resCircRepo' => ['privates', 'App\\Repository\\ReservationCircuitRepository', 'getReservationCircuitRepositoryService', true],
            'resHebRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'reviewRepo' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
        ], [
            'bookingRepo' => 'App\\Repository\\BookingRepository',
            'circuitAvisRepo' => 'App\\Repository\\CircuitAvisRepository',
            'favActRepo' => 'App\\Repository\\FavoriteActivityRepository',
            'favCircRepo' => 'App\\Repository\\FavoriteCircuitRepository',
            'favHebRepo' => 'App\\Repository\\FavoriteHebergementRepository',
            'favPostRepo' => 'App\\Repository\\FavoritePostRepository',
            'favTransRepo' => 'App\\Repository\\FavoriteTransportRepository',
            'paginator' => '?',
            'resCircRepo' => 'App\\Repository\\ReservationCircuitRepository',
            'resHebRepo' => 'App\\Repository\\ReservationRepository',
            'reviewRepo' => 'App\\Repository\\ReviewRepository',
        ]);

        if (isset($container->privates['.service_locator.EwosNoV'])) {
            return $container->privates['.service_locator.EwosNoV'];
        }

        return $container->privates['.service_locator.EwosNoV'] = $instance;
    }
}
