<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G3tdkTYService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.g3tdkTY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservation' => ['privates', '.errored..service_locator.g3tdkTY.App\\Entity\\ReservationCircuit', NULL, 'Cannot autowire service ".service_locator.g3tdkTY": it needs an instance of "App\\Entity\\ReservationCircuit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'reservation' => 'App\\Entity\\ReservationCircuit',
        ]);

        if (isset($container->privates['.service_locator.g3tdkTY'])) {
            return $container->privates['.service_locator.g3tdkTY'];
        }

        return $container->privates['.service_locator.g3tdkTY'] = $instance;
    }
}
