<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sf1N6fAService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.sf1N6fA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\TransportOfferRepository', 'getTransportOfferRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\TransportOfferRepository',
        ]);

        if (isset($container->privates['.service_locator.sf1N6fA'])) {
            return $container->privates['.service_locator.sf1N6fA'];
        }

        return $container->privates['.service_locator.sf1N6fA'] = $instance;
    }
}
