<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7FgXvService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator._I7FgXv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\ForumPostRepository', 'getForumPostRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\ForumPostRepository',
        ]);

        if (isset($container->privates['.service_locator._I7FgXv'])) {
            return $container->privates['.service_locator._I7FgXv'];
        }

        return $container->privates['.service_locator._I7FgXv'] = $instance;
    }
}
