<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S5mr1z8Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.S5mr1z8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S5mr1z8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ai' => ['privates', 'App\\Service\\Api\\AiService', 'getAiServiceService', true],
            'exchange' => ['privates', 'App\\Service\\Api\\ExchangeRateService', 'getExchangeRateServiceService', true],
            'flights' => ['privates', 'App\\Service\\Api\\FlightApiService', 'getFlightApiServiceService', true],
            'geo' => ['privates', 'App\\Service\\Api\\GeolocationService', 'getGeolocationServiceService', true],
            'moderation' => ['privates', 'App\\Service\\Api\\ModerationService', 'getModerationServiceService', true],
            'payment' => ['privates', 'App\\Service\\Api\\PaymentService', 'getPaymentService2Service', true],
            'places' => ['privates', 'App\\Service\\Api\\PlacesApiService', 'getPlacesApiServiceService', true],
            'qrcode' => ['privates', 'App\\Service\\Api\\QrCodeService', 'getQrCodeServiceService', true],
            'skyscanner' => ['privates', 'App\\Service\\Api\\SkyscannerApiService', 'getSkyscannerApiServiceService', true],
            'translate' => ['privates', 'App\\Service\\Api\\TranslationService', 'getTranslationServiceService', true],
            'weather' => ['privates', 'App\\Service\\Api\\WeatherApiService', 'getWeatherApiServiceService', true],
        ], [
            'ai' => 'App\\Service\\Api\\AiService',
            'exchange' => 'App\\Service\\Api\\ExchangeRateService',
            'flights' => 'App\\Service\\Api\\FlightApiService',
            'geo' => 'App\\Service\\Api\\GeolocationService',
            'moderation' => 'App\\Service\\Api\\ModerationService',
            'payment' => 'App\\Service\\Api\\PaymentService',
            'places' => 'App\\Service\\Api\\PlacesApiService',
            'qrcode' => 'App\\Service\\Api\\QrCodeService',
            'skyscanner' => 'App\\Service\\Api\\SkyscannerApiService',
            'translate' => 'App\\Service\\Api\\TranslationService',
            'weather' => 'App\\Service\\Api\\WeatherApiService',
        ]);
    }
}
