<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iyq7osOService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Iyq7osO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Iyq7osO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profil' => ['privates', '.errored..service_locator.Iyq7osO.App\\Entity\\ProfilVoyageur', NULL, 'Cannot autowire service ".service_locator.Iyq7osO": it needs an instance of "App\\Entity\\ProfilVoyageur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'profil' => 'App\\Entity\\ProfilVoyageur',
        ]);
    }
}
