<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9m1xRz2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.9m1xRz2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paymentService' => ['privates', 'App\\Service\\PaymentService', 'getPaymentServiceService', true],
            'repo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'em' => '?',
            'paymentService' => 'App\\Service\\PaymentService',
            'repo' => 'App\\Repository\\ReservationRepository',
        ]);

        if (isset($container->privates['.service_locator.9m1xRz2'])) {
            return $container->privates['.service_locator.9m1xRz2'];
        }

        return $container->privates['.service_locator.9m1xRz2'] = $instance;
    }
}
