<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBFFWwuService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qBFFWwu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepo' => ['privates', 'App\\Repository\\ForumCommentRepository', 'getForumCommentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favRepo' => ['privates', 'App\\Repository\\FavoritePostRepository', 'getFavoritePostRepositoryService', true],
            'likeRepo' => ['privates', 'App\\Repository\\LikeDislikeRepository', 'getLikeDislikeRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\ForumPostRepository', 'getForumPostRepositoryService', true],
        ], [
            'commentRepo' => 'App\\Repository\\ForumCommentRepository',
            'em' => '?',
            'favRepo' => 'App\\Repository\\FavoritePostRepository',
            'likeRepo' => 'App\\Repository\\LikeDislikeRepository',
            'repo' => 'App\\Repository\\ForumPostRepository',
        ]);

        if (isset($container->privates['.service_locator.qBFFWwu'])) {
            return $container->privates['.service_locator.qBFFWwu'];
        }

        return $container->privates['.service_locator.qBFFWwu'] = $instance;
    }
}
