<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QTDQpFeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.QTDQpFe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favActRepo' => ['privates', 'App\\Repository\\FavoriteActivityRepository', 'getFavoriteActivityRepositoryService', true],
            'favCircRepo' => ['privates', 'App\\Repository\\FavoriteCircuitRepository', 'getFavoriteCircuitRepositoryService', true],
            'favHebRepo' => ['privates', 'App\\Repository\\FavoriteHebergementRepository', 'getFavoriteHebergementRepositoryService', true],
            'favPostRepo' => ['privates', 'App\\Repository\\FavoritePostRepository', 'getFavoritePostRepositoryService', true],
            'favTransRepo' => ['privates', 'App\\Repository\\FavoriteTransportRepository', 'getFavoriteTransportRepositoryService', true],
        ], [
            'em' => '?',
            'favActRepo' => 'App\\Repository\\FavoriteActivityRepository',
            'favCircRepo' => 'App\\Repository\\FavoriteCircuitRepository',
            'favHebRepo' => 'App\\Repository\\FavoriteHebergementRepository',
            'favPostRepo' => 'App\\Repository\\FavoritePostRepository',
            'favTransRepo' => 'App\\Repository\\FavoriteTransportRepository',
        ]);

        if (isset($container->privates['.service_locator.QTDQpFe'])) {
            return $container->privates['.service_locator.QTDQpFe'];
        }

        return $container->privates['.service_locator.QTDQpFe'] = $instance;
    }
}
