<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5admz53Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5admz53' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\BookingRepository',
        ]);

        if (isset($container->privates['.service_locator.5admz53'])) {
            return $container->privates['.service_locator.5admz53'];
        }

        return $container->privates['.service_locator.5admz53'] = $instance;
    }
}
