<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AfiYJR4Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.afiYJR4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favRepo' => ['privates', 'App\\Repository\\FavoritePostRepository', 'getFavoritePostRepositoryService', true],
        ], [
            'em' => '?',
            'favRepo' => 'App\\Repository\\FavoritePostRepository',
        ]);

        if (isset($container->privates['.service_locator.afiYJR4'])) {
            return $container->privates['.service_locator.afiYJR4'];
        }

        return $container->privates['.service_locator.afiYJR4'] = $instance;
    }
}
