<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AD2q_LBService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.AD2q.lB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AD2q.lB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'hebRepo' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', true],
            'resRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'avisRepo' => 'App\\Repository\\AvisRepository',
            'hebRepo' => 'App\\Repository\\HebergementRepository',
            'resRepo' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
