<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKEZ5yEService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.RKEZ5yE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RKEZ5yE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'openAIService' => ['privates', 'App\\Service\\OpenAIService', 'getOpenAIServiceService', true],
        ], [
            'openAIService' => 'App\\Service\\OpenAIService',
        ]);
    }
}
