<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__H4rayeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator..h4raye' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\ProfilVoyageurRepository', 'getProfilVoyageurRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\ProfilVoyageurRepository',
        ]);

        if (isset($container->privates['.service_locator..h4raye'])) {
            return $container->privates['.service_locator..h4raye'];
        }

        return $container->privates['.service_locator..h4raye'] = $instance;
    }
}
