<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZK9LnE9Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.zK9LnE9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zK9LnE9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actRepo' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'circRepo' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
            'forumRepo' => ['privates', 'App\\Repository\\ForumPostRepository', 'getForumPostRepositoryService', true],
            'hebRepo' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', true],
        ], [
            'actRepo' => 'App\\Repository\\ActivityRepository',
            'circRepo' => 'App\\Repository\\CircuitRepository',
            'forumRepo' => 'App\\Repository\\ForumPostRepository',
            'hebRepo' => 'App\\Repository\\HebergementRepository',
        ]);
    }
}
