<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Subscription_SubscriptionManagerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.subscription.subscription_manager' shared service.
     *
     * @return \ApiPlatform\GraphQl\Subscription\SubscriptionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Subscription'.\DIRECTORY_SEPARATOR.'SubscriptionManagerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'IdentifierTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'SortTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Subscription'.\DIRECTORY_SEPARATOR.'SubscriptionManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Subscription'.\DIRECTORY_SEPARATOR.'SubscriptionIdentifierGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Subscription'.\DIRECTORY_SEPARATOR.'SubscriptionIdentifierGenerator.php';

        $a = ($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container));

        if (isset($container->privates['api_platform.graphql.subscription.subscription_manager'])) {
            return $container->privates['api_platform.graphql.subscription.subscription_manager'];
        }
        $b = ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container));

        if (isset($container->privates['api_platform.graphql.subscription.subscription_manager'])) {
            return $container->privates['api_platform.graphql.subscription.subscription_manager'];
        }

        $instance = new \ApiPlatform\GraphQl\Subscription\SubscriptionManager(($container->privates['api_platform.graphql.cache.subscription'] ?? self::getApiPlatform_Graphql_Cache_SubscriptionService($container)), ($container->privates['api_platform.graphql.subscription.subscription_identifier_generator'] ??= new \ApiPlatform\GraphQl\Subscription\SubscriptionIdentifierGenerator()), ($container->privates['api_platform.graphql.resolver.stage.serialize'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_SerializeService')), $a, $b);

        if (isset($container->privates['api_platform.graphql.subscription.subscription_manager'])) {
            return $container->privates['api_platform.graphql.subscription.subscription_manager'];
        }

        return $container->privates['api_platform.graphql.subscription.subscription_manager'] = $instance;
    }
}
