<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Resolver_Factory_ItemService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.resolver.factory.item' shared service.
     *
     * @return \ApiPlatform\GraphQl\Resolver\Factory\ItemResolverFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ResolverFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ItemResolverFactory.php';

        return $container->privates['api_platform.graphql.resolver.factory.item'] = new \ApiPlatform\GraphQl\Resolver\Factory\ItemResolverFactory(($container->privates['api_platform.graphql.resolver.stage.read'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_ReadService')), ($container->privates['api_platform.graphql.resolver.stage.security'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_SecurityService')), ($container->privates['api_platform.graphql.resolver.stage.security_post_denormalize'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_SecurityPostDenormalizeService')), ($container->privates['api_platform.graphql.resolver.stage.serialize'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_SerializeService')), ($container->privates['api_platform.graphql.query_resolver_locator'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])), ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container)));
    }
}
