<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_FieldsBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.fields_builder' shared service.
     *
     * @return \ApiPlatform\GraphQl\Type\FieldsBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'FieldsBuilderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'FieldsBuilder.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TypesContainerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TypesContainer.php';

        $a = ($container->privates['api_platform.graphql.type_builder'] ?? $container->load('getApiPlatform_Graphql_TypeBuilderService'));

        if (isset($container->privates['api_platform.graphql.fields_builder'])) {
            return $container->privates['api_platform.graphql.fields_builder'];
        }
        $b = ($container->privates['api_platform.graphql.type_converter'] ?? $container->load('getApiPlatform_Graphql_TypeConverterService'));

        if (isset($container->privates['api_platform.graphql.fields_builder'])) {
            return $container->privates['api_platform.graphql.fields_builder'];
        }

        $instance = new \ApiPlatform\GraphQl\Type\FieldsBuilder(($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container)), ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container)), ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), ($container->privates['api_platform.graphql.types_container'] ??= new \ApiPlatform\GraphQl\Type\TypesContainer()), $a, $b, ($container->privates['api_platform.graphql.resolver.factory.item'] ?? $container->load('getApiPlatform_Graphql_Resolver_Factory_ItemService')), ($container->privates['api_platform.graphql.resolver.factory.collection'] ?? $container->load('getApiPlatform_Graphql_Resolver_Factory_CollectionService')), ($container->privates['api_platform.graphql.resolver.factory.item_mutation'] ?? $container->load('getApiPlatform_Graphql_Resolver_Factory_ItemMutationService')), ($container->privates['api_platform.graphql.resolver.factory.item_subscription'] ?? $container->load('getApiPlatform_Graphql_Resolver_Factory_ItemSubscriptionService')), ($container->privates['api_platform.filter_locator'] ?? self::getApiPlatform_FilterLocatorService($container)), ($container->privates['api_platform.pagination'] ?? $container->load('getApiPlatform_PaginationService')), ($container->privates['serializer.name_converter.metadata_aware'] ?? self::getSerializer_NameConverter_MetadataAwareService($container)), '_');

        if (isset($container->privates['api_platform.graphql.fields_builder'])) {
            return $container->privates['api_platform.graphql.fields_builder'];
        }

        return $container->privates['api_platform.graphql.fields_builder'] = $instance;
    }
}
