<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyticsServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\AnalyticsService' shared autowired service.
     *
     * @return \App\Service\AnalyticsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AnalyticsService.php';

        return $container->privates['App\\Service\\AnalyticsService'] = new \App\Service\AnalyticsService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CircuitRepository'] ?? $container->load('getCircuitRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')), ($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), ($container->privates['App\\Repository\\ReservationCircuitRepository'] ?? $container->load('getReservationCircuitRepositoryService')), ($container->privates['App\\Repository\\HebergementRepository'] ?? $container->load('getHebergementRepositoryService')));
    }
}
