<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_TypesFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.types_factory' shared service.
     *
     * @return \ApiPlatform\GraphQl\Type\TypesFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TypesFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TypesFactory.php';

        return $container->privates['api_platform.graphql.types_factory'] = new \ApiPlatform\GraphQl\Type\TypesFactory(($container->privates['api_platform.graphql.type_locator'] ?? $container->load('getApiPlatform_Graphql_TypeLocatorService')), ['api_platform.graphql.iterable_type', 'api_platform.graphql.upload_type']);
    }
}
