<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityFileSystemService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'ActivityFileSystem' shared service.
     *
     * @return \Gaufrette\Filesystem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'FilesystemInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Filesystem.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Adapter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'StreamFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'ChecksumCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'SizeCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'MimeTypeProvider.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'Local.php';

        return $container->services['ActivityFileSystem'] = new \Gaufrette\Filesystem(($container->privates['gaufrette.local_activity_adapter'] ??= new \Gaufrette\Adapter\Local((\dirname(__DIR__, 4).'/public/uploads/activities'), true)));
    }
}
