<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Resolver_Stage_SerializeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.resolver.stage.serialize' shared service.
     *
     * @return \ApiPlatform\GraphQl\Resolver\Stage\SerializeStage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Stage'.\DIRECTORY_SEPARATOR.'SerializeStageInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'IdentifierTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Stage'.\DIRECTORY_SEPARATOR.'SerializeStage.php';

        return $container->privates['api_platform.graphql.resolver.stage.serialize'] = new \ApiPlatform\GraphQl\Resolver\Stage\SerializeStage(($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['api_platform.graphql.serializer.context_builder'] ?? $container->load('getApiPlatform_Graphql_Serializer_ContextBuilderService')), ($container->privates['api_platform.pagination'] ?? $container->load('getApiPlatform_PaginationService')));
    }
}
