<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EsALWiC.App\Entity\Booking' shared service.
     *
     * @return \App\Entity\Booking
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EsALWiC": it needs an instance of "App\\Entity\\Booking" but this type has been excluded in "config/services.yaml".');
    }
}
