<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBootstrapSymlinkSassCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Mopa\Bundle\BootstrapBundle\Command\BootstrapSymlinkSassCommand' shared service.
     *
     * @return \Mopa\Bundle\BootstrapBundle\Command\BootstrapSymlinkSassCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mopa'.\DIRECTORY_SEPARATOR.'bootstrap-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'BaseBootstrapSymlinkCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mopa'.\DIRECTORY_SEPARATOR.'bootstrap-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'BootstrapSymlinkSassCommand.php';

        $container->services['Mopa\\Bundle\\BootstrapBundle\\Command\\BootstrapSymlinkSassCommand'] = $instance = new \Mopa\Bundle\BootstrapBundle\Command\BootstrapSymlinkSassCommand('Resources/public/bootstrap');

        $instance->setName('mopa:bootstrap:symlink:sass');

        return $instance;
    }
}
