<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCharsetAnalyzerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Configuration\CharsetAnalyzer' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\CharsetAnalyzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'AnalyzerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Configuration'.\DIRECTORY_SEPARATOR.'CharsetAnalyzer.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'];
        }
        $b = ($container->privates['AhmedBhs\\DoctrineDoctor\\Utils\\DatabasePlatformDetector'] ?? $container->load('getDatabasePlatformDetectorService'));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'];
        }
        $c = ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'] ?? $container->load('getPlatformAnalysisStrategyFactoryService'));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'];
        }

        $instance = new \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\CharsetAnalyzer($a, ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), $b, $c, ($container->privates['doctrine_doctor.null_logger'] ??= new \Psr\Log\NullLogger()));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'];
        }

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CharsetAnalyzer'] = $instance;
    }
}
