<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatatables_ColumnLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'datatables.column_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['datatables.column_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Omines\\DataTablesBundle\\Column\\TwigColumn' => [false, 'Omines\\DataTablesBundle\\Column\\TwigColumn', 'getTwigColumnService', true],
            'Omines\\DataTablesBundle\\Column\\TwigStringColumn' => [false, 'Omines\\DataTablesBundle\\Column\\TwigStringColumn', 'getTwigStringColumnService', true],
        ], [
            'Omines\\DataTablesBundle\\Column\\TwigColumn' => '?',
            'Omines\\DataTablesBundle\\Column\\TwigStringColumn' => '?',
        ]);
    }
}
