<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataTableFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Omines\DataTablesBundle\DataTableFactory' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\DataTableFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataTableFactory.php';

        return $container->services['Omines\\DataTablesBundle\\DataTableFactory'] = new \Omines\DataTablesBundle\DataTableFactory($container->parameters['datatables.config'], ($container->privates['Omines\\DataTablesBundle\\Twig\\TwigRenderer'] ?? $container->load('getTwigRendererService')), ($container->privates['Omines\\DataTablesBundle\\DependencyInjection\\Instantiator'] ?? $container->load('getInstantiatorService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->privates['Omines\\DataTablesBundle\\Exporter\\DataTableExporterManager'] ?? $container->load('getDataTableExporterManagerService')));
    }
}
