<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExchangeRateService2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ExchangeRateService' shared autowired service.
     *
     * @return \App\Service\ExchangeRateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ExchangeRateService.php';

        return $container->privates['App\\Service\\ExchangeRateService'] = new \App\Service\ExchangeRateService(NULL, ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
