<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForumCommentServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ForumCommentService' shared autowired service.
     *
     * @return \App\Service\ForumCommentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ForumCommentService.php';

        return $container->privates['App\\Service\\ForumCommentService'] = new \App\Service\ForumCommentService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ForumCommentRepository'] ?? $container->load('getForumCommentRepositoryService')), ($container->privates['App\\Repository\\LikeDislikeRepository'] ?? $container->load('getLikeDislikeRepositoryService')));
    }
}
