<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForumAjaxControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\ForumAjaxController' shared autowired service.
     *
     * @return \App\Controller\ForumAjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ForumAjaxController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'ModerationService.php';

        $container->services['App\\Controller\\ForumAjaxController'] = $instance = new \App\Controller\ForumAjaxController(($container->privates['App\\Service\\ForumCommentService'] ?? $container->load('getForumCommentServiceService')), ($container->privates['App\\Repository\\ForumCommentRepository'] ?? $container->load('getForumCommentRepositoryService')), ($container->privates['App\\Repository\\ForumPostRepository'] ?? $container->load('getForumPostRepositoryService')), ($container->privates['App\\Repository\\LikeDislikeRepository'] ?? $container->load('getLikeDislikeRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\Api\\ModerationService'] ??= new \App\Service\Api\ModerationService()), ($container->privates['security.csrf.token_manager'] ?? self::getSecurity_Csrf_TokenManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ForumAjaxController', $container));

        return $instance;
    }
}
