<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_ExtensionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'form.extension' shared service.
     *
     * @return \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';

        $instance = new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Form\\ActivityAdminType' => ['privates', 'App\\Form\\ActivityAdminType', 'getActivityAdminTypeService', true],
            'App\\Form\\CircuitAdminType' => ['privates', 'App\\Form\\CircuitAdminType', 'getCircuitAdminTypeService', true],
            'App\\Form\\ForumSujetType' => ['privates', 'App\\Form\\ForumSujetType', 'getForumSujetTypeService', true],
            'App\\Form\\HebergementAdminType' => ['privates', 'App\\Form\\HebergementAdminType', 'getHebergementAdminTypeService', true],
            'App\\Form\\ProfilVoyageurType' => ['privates', 'App\\Form\\ProfilVoyageurType', 'getProfilVoyageurTypeService', true],
            'App\\Form\\TransportAdminType' => ['privates', 'App\\Form\\TransportAdminType', 'getTransportAdminTypeService', true],
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType' => ['privates', 'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType', 'getCrudAutocompleteTypeService', true],
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudFormType' => ['privates', 'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudFormType', 'getCrudFormTypeService', true],
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\EaMoneyType' => ['privates', 'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\EaMoneyType', 'getEaMoneyTypeService', true],
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\FileUploadType' => ['privates', 'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\FileUploadType', 'getFileUploadTypeService', true],
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\FiltersFormType' => ['privates', 'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\FiltersFormType', 'getFiltersFormTypeService', true],
            'Liip\\ImagineBundle\\Form\\Type\\ImageType' => ['privates', 'liip_imagine.form.type.image', 'getLiipImagine_Form_Type_ImageService', true],
            'Mopa\\Bundle\\BootstrapBundle\\Form\\Type\\FormActionsType' => ['privates', 'mopa_bootstrap.form.type.form_actions', 'getMopaBootstrap_Form_Type_FormActionsService', true],
            'Mopa\\Bundle\\BootstrapBundle\\Form\\Type\\TabType' => ['privates', 'mopa_bootstrap.form.type.tab', 'getMopaBootstrap_Form_Type_TabService', true],
            'Sonata\\AdminBundle\\Form\\Type\\AdminType' => ['privates', 'sonata.admin.form.type.admin', 'getSonata_Admin_Form_Type_AdminService', true],
            'Sonata\\AdminBundle\\Form\\Type\\ChoiceFieldMaskType' => ['privates', 'sonata.admin.doctrine_orm.form.type.choice_field_mask', 'getSonata_Admin_DoctrineOrm_Form_Type_ChoiceFieldMaskService', true],
            'Sonata\\AdminBundle\\Form\\Type\\CollectionType' => ['privates', 'sonata.admin.form.type.collection', 'getSonata_Admin_Form_Type_CollectionService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\ChoiceType' => ['privates', 'sonata.admin.form.filter.type.choice', 'getSonata_Admin_Form_Filter_Type_ChoiceService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateRangeType' => ['privates', 'sonata.admin.form.filter.type.daterange', 'getSonata_Admin_Form_Filter_Type_DaterangeService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateTimeRangeType' => ['privates', 'sonata.admin.form.filter.type.datetime_range', 'getSonata_Admin_Form_Filter_Type_DatetimeRangeService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateTimeType' => ['privates', 'sonata.admin.form.filter.type.datetime', 'getSonata_Admin_Form_Filter_Type_DatetimeService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateType' => ['privates', 'sonata.admin.form.filter.type.date', 'getSonata_Admin_Form_Filter_Type_DateService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DefaultType' => ['privates', 'sonata.admin.form.filter.type.default', 'getSonata_Admin_Form_Filter_Type_DefaultService', true],
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\NumberType' => ['privates', 'sonata.admin.form.filter.type.number', 'getSonata_Admin_Form_Filter_Type_NumberService', true],
            'Sonata\\AdminBundle\\Form\\Type\\ModelAutocompleteType' => ['privates', 'sonata.admin.form.type.model_autocomplete', 'getSonata_Admin_Form_Type_ModelAutocompleteService', true],
            'Sonata\\AdminBundle\\Form\\Type\\ModelHiddenType' => ['privates', 'sonata.admin.form.type.model_hidden', 'getSonata_Admin_Form_Type_ModelHiddenService', true],
            'Sonata\\AdminBundle\\Form\\Type\\ModelListType' => ['privates', 'sonata.admin.form.type.model_list', 'getSonata_Admin_Form_Type_ModelListService', true],
            'Sonata\\AdminBundle\\Form\\Type\\ModelReferenceType' => ['privates', 'sonata.admin.form.type.model_reference', 'getSonata_Admin_Form_Type_ModelReferenceService', true],
            'Sonata\\AdminBundle\\Form\\Type\\ModelType' => ['privates', 'sonata.admin.form.type.model_choice', 'getSonata_Admin_Form_Type_ModelChoiceService', true],
            'Sonata\\BlockBundle\\Form\\Type\\ContainerTemplateType' => ['privates', 'sonata.block.form.type.container_template', 'getSonata_Block_Form_Type_ContainerTemplateService', true],
            'Sonata\\BlockBundle\\Form\\Type\\ServiceListType' => ['privates', 'sonata.block.form.type.block', 'getSonata_Block_Form_Type_BlockService', true],
            'Sonata\\Form\\Type\\BooleanType' => ['privates', 'sonata.form.type.boolean', 'getSonata_Form_Type_BooleanService', true],
            'Sonata\\Form\\Type\\CollectionType' => ['privates', 'sonata.form.type.collection', 'getSonata_Form_Type_CollectionService', true],
            'Sonata\\Form\\Type\\DatePickerType' => ['privates', 'sonata.form.type.date_picker', 'getSonata_Form_Type_DatePickerService', true],
            'Sonata\\Form\\Type\\DateRangePickerType' => ['privates', 'sonata.form.type.date_range_picker', 'getSonata_Form_Type_DateRangePickerService', true],
            'Sonata\\Form\\Type\\DateRangeType' => ['privates', 'sonata.form.type.date_range', 'getSonata_Form_Type_DateRangeService', true],
            'Sonata\\Form\\Type\\DateTimePickerType' => ['privates', 'sonata.form.type.datetime_picker', 'getSonata_Form_Type_DatetimePickerService', true],
            'Sonata\\Form\\Type\\DateTimeRangePickerType' => ['privates', 'sonata.form.type.datetime_range_picker', 'getSonata_Form_Type_DatetimeRangePickerService', true],
            'Sonata\\Form\\Type\\DateTimeRangeType' => ['privates', 'sonata.form.type.datetime_range', 'getSonata_Form_Type_DatetimeRangeService', true],
            'Sonata\\Form\\Type\\ImmutableArrayType' => ['privates', 'sonata.form.type.array', 'getSonata_Form_Type_ArrayService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
            'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => ['services', 'vich_uploader.form.type.file', 'getVichUploader_Form_Type_FileService', true],
            'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => ['services', 'vich_uploader.form.type.image', 'getVichUploader_Form_Type_ImageService', true],
        ], [
            'App\\Form\\ActivityAdminType' => '?',
            'App\\Form\\CircuitAdminType' => '?',
            'App\\Form\\ForumSujetType' => '?',
            'App\\Form\\HebergementAdminType' => '?',
            'App\\Form\\ProfilVoyageurType' => '?',
            'App\\Form\\TransportAdminType' => '?',
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType' => '?',
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudFormType' => '?',
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\EaMoneyType' => '?',
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\FileUploadType' => '?',
            'EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\FiltersFormType' => '?',
            'Liip\\ImagineBundle\\Form\\Type\\ImageType' => '?',
            'Mopa\\Bundle\\BootstrapBundle\\Form\\Type\\FormActionsType' => '?',
            'Mopa\\Bundle\\BootstrapBundle\\Form\\Type\\TabType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\AdminType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\ChoiceFieldMaskType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\CollectionType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\ChoiceType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateRangeType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateTimeRangeType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateTimeType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DateType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\DefaultType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\Filter\\NumberType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\ModelAutocompleteType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\ModelHiddenType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\ModelListType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\ModelReferenceType' => '?',
            'Sonata\\AdminBundle\\Form\\Type\\ModelType' => '?',
            'Sonata\\BlockBundle\\Form\\Type\\ContainerTemplateType' => '?',
            'Sonata\\BlockBundle\\Form\\Type\\ServiceListType' => '?',
            'Sonata\\Form\\Type\\BooleanType' => '?',
            'Sonata\\Form\\Type\\CollectionType' => '?',
            'Sonata\\Form\\Type\\DatePickerType' => '?',
            'Sonata\\Form\\Type\\DateRangePickerType' => '?',
            'Sonata\\Form\\Type\\DateRangeType' => '?',
            'Sonata\\Form\\Type\\DateTimePickerType' => '?',
            'Sonata\\Form\\Type\\DateTimeRangePickerType' => '?',
            'Sonata\\Form\\Type\\DateTimeRangeType' => '?',
            'Sonata\\Form\\Type\\ImmutableArrayType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
            'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => '?',
            'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
            yield 6 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
            yield 7 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Extension\\EaCrudFormTypeExtension'] ?? $container->load('getEaCrudFormTypeExtensionService'));
            yield 8 => ($container->privates['sonata.admin.form.extension.field'] ?? $container->load('getSonata_Admin_Form_Extension_FieldService'));
            yield 9 => ($container->privates['mopa_bootstrap.form.type_extension.embed_form'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\EmbedFormExtension());
            yield 10 => ($container->privates['mopa_bootstrap.form.type_extension.static_text'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\StaticTextExtension());
            yield 11 => ($container->privates['mopa_bootstrap.form.type_extension.help'] ?? $container->load('getMopaBootstrap_Form_TypeExtension_HelpService'));
            yield 12 => ($container->privates['mopa_bootstrap.form.type_extension.legend'] ?? $container->load('getMopaBootstrap_Form_TypeExtension_LegendService'));
            yield 13 => ($container->privates['mopa_bootstrap.form.type_extension.error'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\ErrorTypeFormTypeExtension(['error_type' => NULL]));
            yield 14 => ($container->privates['mopa_bootstrap.form.type_extension.widget'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\WidgetFormTypeExtension(['checkbox_label' => 'skip']));
            yield 15 => ($container->privates['mopa_bootstrap.form.type_extension.horizontal'] ?? $container->load('getMopaBootstrap_Form_TypeExtension_HorizontalService'));
            yield 16 => ($container->privates['mopa_bootstrap.form.type_extension.widget_collection'] ?? $container->load('getMopaBootstrap_Form_TypeExtension_WidgetCollectionService'));
            yield 17 => ($container->privates['mopa_bootstrap.form.type_extension.tabbed'] ?? $container->load('getMopaBootstrap_Form_TypeExtension_TabbedService'));
        }, 18), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\CollectionType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Extension\\CollectionTypeExtension'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Form\Extension\CollectionTypeExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sonata.admin.form.extension.choice'] ??= new \Sonata\AdminBundle\Form\Extension\ChoiceTypeExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ButtonType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['mopa_bootstrap.form.type_extension.offset_button'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\OffsetButtonExtension());
            yield 1 => ($container->privates['mopa_bootstrap.form.type_extension.button'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\IconButtonExtension());
        }, 2), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\DateType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['mopa_bootstrap.form.type_extension.date'] ?? $container->load('getMopaBootstrap_Form_TypeExtension_DateService'));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\DateTimeType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['mopa_bootstrap.form.type_extension.datetime'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\DatetimeTypeExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\TimeType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['mopa_bootstrap.form.type_extension.time'] ??= new \Mopa\Bundle\BootstrapBundle\Form\Extension\TimeTypeExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\TextType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['exercise_html_purifier.form.text_type_extension'] ?? $container->load('getExerciseHtmlPurifier_Form_TextTypeExtensionService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2));

        if (isset($container->privates['form.extension'])) {
            return $container->privates['form.extension'];
        }

        return $container->privates['form.extension'] = $instance;
    }
}
