<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeocodingServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\GeocodingService' shared autowired service.
     *
     * @return \App\Service\GeocodingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GeocodingService.php';

        return $container->privates['App\\Service\\GeocodingService'] = new \App\Service\GeocodingService($container->getEnv('default::APP_GEOAPIFY_API_KEY'), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
