<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHuggingFaceServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\HuggingFaceService' shared autowired service.
     *
     * @return \App\Service\HuggingFaceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HuggingFaceService.php';

        return $container->privates['App\\Service\\HuggingFaceService'] = new \App\Service\HuggingFaceService($container->getEnv('HUGGINGFACE_API_KEY'), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
