<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_MatcherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'knp_menu.matcher' shared service.
     *
     * @return \Knp\Menu\Matcher\Matcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-menu'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Knp'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'Matcher'.\DIRECTORY_SEPARATOR.'MatcherInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-menu'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Knp'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'Matcher'.\DIRECTORY_SEPARATOR.'Matcher.php';

        return $container->services['knp_menu.matcher'] = new \Knp\Menu\Matcher\Matcher(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['knp_menu.voter.callback'] ??= new \Knp\Menu\Matcher\Voter\CallbackVoter());
            yield 1 => ($container->privates['knp_menu.voter.router'] ?? $container->load('getKnpMenu_Voter_RouterService'));
            yield 2 => ($container->privates['sonata.admin.menu.matcher.voter.admin'] ?? $container->load('getSonata_Admin_Menu_Matcher_Voter_AdminService'));
            yield 3 => ($container->privates['sonata.admin.menu.matcher.voter.active'] ??= new \Sonata\AdminBundle\Menu\Matcher\Voter\ActiveVoter());
        }, 4));
    }
}
