<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpPaginator_Helper_ProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'knp_paginator.helper.processor' shared service.
     *
     * @return \Knp\Bundle\PaginatorBundle\Helper\Processor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-paginator-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'Processor.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['knp_paginator.helper.processor'])) {
            return $container->privates['knp_paginator.helper.processor'];
        }

        $instance = new \Knp\Bundle\PaginatorBundle\Helper\Processor($a, ($container->services['translator'] ?? self::getTranslatorService($container)));

        if (isset($container->privates['knp_paginator.helper.processor'])) {
            return $container->privates['knp_paginator.helper.processor'];
        }

        return $container->privates['knp_paginator.helper.processor'] = $instance;
    }
}
