<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_FactoryExtension_RoutingService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'knp_menu.factory_extension.routing' shared service.
     *
     * @return \Knp\Menu\Integration\Symfony\RoutingExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-menu'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Knp'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-menu'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Knp'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'Integration'.\DIRECTORY_SEPARATOR.'Symfony'.\DIRECTORY_SEPARATOR.'RoutingExtension.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['knp_menu.factory_extension.routing'])) {
            return $container->privates['knp_menu.factory_extension.routing'];
        }

        $instance = new \Knp\Menu\Integration\Symfony\RoutingExtension($a);

        if (isset($container->privates['knp_menu.factory_extension.routing'])) {
            return $container->privates['knp_menu.factory_extension.routing'];
        }

        return $container->privates['knp_menu.factory_extension.routing'] = $instance;
    }
}
