<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMapboxServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\MapboxService' shared autowired service.
     *
     * @return \App\Service\Api\MapboxService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'MapboxService.php';

        return $container->privates['App\\Service\\Api\\MapboxService'] = new \App\Service\Api\MapboxService();
    }
}
