<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMercureNotificationServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\MercureNotificationService' shared autowired service.
     *
     * @return \App\Service\MercureNotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MercureNotificationService.php';

        return $container->privates['App\\Service\\MercureNotificationService'] = new \App\Service\MercureNotificationService(($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)));
    }
}
