<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNLPServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\NLPService' shared autowired service.
     *
     * @return \App\Service\NLPService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NLPService.php';

        return $container->privates['App\\Service\\NLPService'] = new \App\Service\NLPService();
    }
}
