<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_View_TwigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'pagerfanta.view.twig' shared service.
     *
     * @return \Pagerfanta\Twig\View\TwigView
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'View'.\DIRECTORY_SEPARATOR.'ViewInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'View'.\DIRECTORY_SEPARATOR.'View.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'View'.\DIRECTORY_SEPARATOR.'TwigView.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['pagerfanta.view.twig'])) {
            return $container->privates['pagerfanta.view.twig'];
        }

        $instance = new \Pagerfanta\Twig\View\TwigView($a, '@Pagerfanta/default.html.twig');

        if (isset($container->privates['pagerfanta.view.twig'])) {
            return $container->privates['pagerfanta.view.twig'];
        }

        return $container->privates['pagerfanta.view.twig'] = $instance;
    }
}
