<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\PaymentService' shared autowired service.
     *
     * @return \App\Service\PaymentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PaymentService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\PaymentService'])) {
            return $container->privates['App\\Service\\PaymentService'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\Service\\PaymentService'])) {
            return $container->privates['App\\Service\\PaymentService'];
        }

        $instance = new \App\Service\PaymentService($container->getEnv('RESEND_API_KEY'), $a, $b, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), \dirname(__DIR__, 4), ($container->privates['App\\Service\\MercureNotificationService'] ?? $container->load('getMercureNotificationServiceService')));

        if (isset($container->privates['App\\Service\\PaymentService'])) {
            return $container->privates['App\\Service\\PaymentService'];
        }

        return $container->privates['App\\Service\\PaymentService'] = $instance;
    }
}
