<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatformAnalysisStrategyFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Factory\PlatformAnalysisStrategyFactory' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Factory\PlatformAnalysisStrategyFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'PlatformAnalysisStrategyFactory.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'];
        }
        $b = ($container->privates['AhmedBhs\\DoctrineDoctor\\Utils\\DatabasePlatformDetector'] ?? $container->load('getDatabasePlatformDetectorService'));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'];
        }

        $instance = new \AhmedBhs\DoctrineDoctor\Factory\PlatformAnalysisStrategyFactory($a, ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), $b);

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'];
        }

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\PlatformAnalysisStrategyFactory'] = $instance;
    }
}
