<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_TwigRuntimeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'pagerfanta.twig_runtime' shared service.
     *
     * @return \Pagerfanta\Twig\Extension\PagerfantaRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'PagerfantaRuntime.php';

        $a = ($container->services['.container.private.pagerfanta.view_factory'] ?? $container->load('get_Container_Private_Pagerfanta_ViewFactoryService'));

        if (isset($container->privates['pagerfanta.twig_runtime'])) {
            return $container->privates['pagerfanta.twig_runtime'];
        }
        $b = ($container->services['.container.private.pagerfanta.route_generator_factory'] ?? $container->load('get_Container_Private_Pagerfanta_RouteGeneratorFactoryService'));

        if (isset($container->privates['pagerfanta.twig_runtime'])) {
            return $container->privates['pagerfanta.twig_runtime'];
        }

        $instance = new \Pagerfanta\Twig\Extension\PagerfantaRuntime('default', $a, $b);

        if (isset($container->privates['pagerfanta.twig_runtime'])) {
            return $container->privates['pagerfanta.twig_runtime'];
        }

        return $container->privates['pagerfanta.twig_runtime'] = $instance;
    }
}
