<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_MenuBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.menu_builder' shared service.
     *
     * @return \Sonata\AdminBundle\Menu\MenuBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'admin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'MenuBuilder.php';

        $a = ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService'));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $b = ($container->privates['knp_menu.menu_provider.chain'] ?? $container->load('getKnpMenu_MenuProvider_ChainService'));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }

        $instance = new \Sonata\AdminBundle\Menu\MenuBuilder(($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container)), $a, $b, $c);

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }

        return $container->privates['sonata.admin.menu_builder'] = $instance;
    }
}
