<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Menu_GroupProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.menu.group_provider' shared service.
     *
     * @return \Sonata\AdminBundle\Menu\Provider\GroupMenuProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-menu'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Knp'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'MenuProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'admin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'GroupMenuProvider.php';

        $a = ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService'));

        if (isset($container->privates['sonata.admin.menu.group_provider'])) {
            return $container->privates['sonata.admin.menu.group_provider'];
        }
        $b = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['sonata.admin.menu.group_provider'])) {
            return $container->privates['sonata.admin.menu.group_provider'];
        }

        $instance = new \Sonata\AdminBundle\Menu\Provider\GroupMenuProvider($a, ($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container)), $b);

        if (isset($container->privates['sonata.admin.menu.group_provider'])) {
            return $container->privates['sonata.admin.menu.group_provider'];
        }

        return $container->privates['sonata.admin.menu.group_provider'] = $instance;
    }
}
