<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSherpaServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\SherpaService' shared autowired service.
     *
     * @return \App\Service\Api\SherpaService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'SherpaService.php';

        return $container->privates['App\\Service\\Api\\SherpaService'] = new \App\Service\Api\SherpaService();
    }
}
