<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStofDoctrineExtensions_Tool_ActorProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'stof_doctrine_extensions.tool.actor_provider' shared service.
     *
     * @return \Stof\DoctrineExtensionsBundle\Tool\TokenStorageActorProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'gedmo'.\DIRECTORY_SEPARATOR.'doctrine-extensions'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Tool'.\DIRECTORY_SEPARATOR.'ActorProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'stof'.\DIRECTORY_SEPARATOR.'doctrine-extensions-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Tool'.\DIRECTORY_SEPARATOR.'TokenStorageActorProvider.php';

        $a = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['stof_doctrine_extensions.tool.actor_provider'])) {
            return $container->privates['stof_doctrine_extensions.tool.actor_provider'];
        }

        $instance = new \Stof\DoctrineExtensionsBundle\Tool\TokenStorageActorProvider(($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $a);

        if (isset($container->privates['stof_doctrine_extensions.tool.actor_provider'])) {
            return $container->privates['stof_doctrine_extensions.tool.actor_provider'];
        }

        return $container->privates['stof_doctrine_extensions.tool.actor_provider'] = $instance;
    }
}
