<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Block_Command_DebugBlocksService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.block.command.debug_blocks' shared service.
     *
     * @return \Sonata\BlockBundle\Command\DebugBlocksCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'block-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DebugBlocksCommand.php';

        $container->privates['sonata.block.command.debug_blocks'] = $instance = new \Sonata\BlockBundle\Command\DebugBlocksCommand(($container->services['sonata.block.manager'] ?? self::getSonata_Block_ManagerService($container)));

        $instance->setName('debug:sonata:block');
        $instance->setDescription('Debug all blocks available, show default settings of each block');

        return $instance;
    }
}
