<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnsplashServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\UnsplashService' shared autowired service.
     *
     * @return \App\Service\Api\UnsplashService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'UnsplashService.php';

        return $container->privates['App\\Service\\Api\\UnsplashService'] = new \App\Service\Api\UnsplashService($container->getEnv('default::UNSPLASH_ACCESS_KEY'));
    }
}
