<?php

namespace ContainerY183cKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVarDumper_ContextualizedCliDumperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'var_dumper.contextualized_cli_dumper' shared service.
     *
     * @return \Symfony\Component\VarDumper\Dumper\ContextualizedDumper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'var-dumper'.\DIRECTORY_SEPARATOR.'Dumper'.\DIRECTORY_SEPARATOR.'ContextualizedDumper.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'var-dumper'.\DIRECTORY_SEPARATOR.'Dumper'.\DIRECTORY_SEPARATOR.'ContextProvider'.\DIRECTORY_SEPARATOR.'ContextProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'var-dumper'.\DIRECTORY_SEPARATOR.'Dumper'.\DIRECTORY_SEPARATOR.'ContextProvider'.\DIRECTORY_SEPARATOR.'SourceContextProvider.php';

        $a = ($container->privates['var_dumper.contextualized_cli_dumper.inner'] ?? $container->load('getVarDumper_ContextualizedCliDumper_InnerService'));

        if (isset($container->privates['var_dumper.contextualized_cli_dumper'])) {
            return $container->privates['var_dumper.contextualized_cli_dumper'];
        }
        $b = ($container->privates['debug.file_link_formatter'] ?? self::getDebug_FileLinkFormatterService($container));

        if (isset($container->privates['var_dumper.contextualized_cli_dumper'])) {
            return $container->privates['var_dumper.contextualized_cli_dumper'];
        }

        $instance = new \Symfony\Component\VarDumper\Dumper\ContextualizedDumper($a, ['source' => new \Symfony\Component\VarDumper\Dumper\ContextProvider\SourceContextProvider('UTF-8', \dirname(__DIR__, 4), $b)]);

        if (isset($container->privates['var_dumper.contextualized_cli_dumper'])) {
            return $container->privates['var_dumper.contextualized_cli_dumper'];
        }

        return $container->privates['var_dumper.contextualized_cli_dumper'] = $instance;
    }
}
