<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408203345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transport_details DROP FOREIGN KEY fk_transport_offer');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY activity_ibfk_1');
        $this->addSql('ALTER TABLE circuit_destination DROP FOREIGN KEY circuit_destination_ibfk_1');
        $this->addSql('ALTER TABLE circuit_interet DROP FOREIGN KEY circuit_interet_ibfk_1');
        $this->addSql('ALTER TABLE circuit_interet DROP FOREIGN KEY circuit_interet_ibfk_2');
        $this->addSql('ALTER TABLE circuit_personnalise DROP FOREIGN KEY circuit_personnalise_ibfk_1');
        $this->addSql('ALTER TABLE circuit_review DROP FOREIGN KEY circuit_review_ibfk_2');
        $this->addSql('ALTER TABLE circuit_review DROP FOREIGN KEY circuit_review_ibfk_1');
        $this->addSql('ALTER TABLE forum_reaction DROP FOREIGN KEY fk_reaction_post');
        $this->addSql('ALTER TABLE jour_circuit DROP FOREIGN KEY jour_circuit_ibfk_1');
        $this->addSql('ALTER TABLE password_reset_tokens DROP FOREIGN KEY password_reset_tokens_ibfk_1');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY payment_ibfk_1');
        $this->addSql('ALTER TABLE taxi_details DROP FOREIGN KEY fk_taxi_offer');
        $this->addSql('DROP TABLE car');
        $this->addSql('DROP TABLE car_rental_details');
        $this->addSql('DROP TABLE centre_interet');
        $this->addSql('DROP TABLE chatbot_faq');
        $this->addSql('DROP TABLE circuit_destination');
        $this->addSql('DROP TABLE circuit_interet');
        $this->addSql('DROP TABLE circuit_personnalise');
        $this->addSql('DROP TABLE circuit_review');
        $this->addSql('DROP TABLE forum_reaction');
        $this->addSql('DROP TABLE game_reward');
        $this->addSql('DROP TABLE jour_circuit');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE offer');
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE price_alert');
        $this->addSql('DROP TABLE price_cache');
        $this->addSql('DROP TABLE price_provider');
        $this->addSql('DROP TABLE price_search_history');
        $this->addSql('DROP TABLE taxi_details');
        $this->addSql('DROP INDEX place_id ON activity');
        $this->addSql('ALTER TABLE activity DROP place_id, DROP user_id, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE price price DOUBLE PRECISION NOT NULL, CHANGE duration duration VARCHAR(50) DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE lieu lieu VARCHAR(100) DEFAULT NULL, CHANGE actif actif TINYINT(1) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE image image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE avis_hebergement CHANGE commentaire commentaire LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE avis_hebergement RENAME INDEX id_hebergement TO IDX_17BB90335040106B');
        $this->addSql('ALTER TABLE avis_hebergement RENAME INDEX user_id TO IDX_17BB9033A76ED395');
        $this->addSql('ALTER TABLE avis_transport CHANGE rating rating INT NOT NULL, CHANGE comment comment LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE avis_transport ADD CONSTRAINT FK_C0FE3EEF53C674EE FOREIGN KEY (offer_id) REFERENCES transport_details (transport_id)');
        $this->addSql('ALTER TABLE avis_transport ADD CONSTRAINT FK_C0FE3EEFA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('CREATE INDEX IDX_C0FE3EEF53C674EE ON avis_transport (offer_id)');
        $this->addSql('CREATE INDEX IDX_C0FE3EEFA76ED395 ON avis_transport (user_id)');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY booking_ibfk_2');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY booking_ibfk_1');
        $this->addSql('DROP INDEX idx_booking_payment_status ON booking');
        $this->addSql('DROP INDEX idx_booking_status ON booking');
        $this->addSql('ALTER TABLE booking DROP payment_status, DROP payment_ref, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE client_phone client_phone VARCHAR(50) DEFAULT NULL, CHANGE status status VARCHAR(50) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE payment_intent_id payment_intent_id VARCHAR(255) DEFAULT NULL, CHANGE payment_method payment_method VARCHAR(50) DEFAULT NULL, CHANGE booking_reference booking_reference VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE booking RENAME INDEX activity_id TO IDX_E00CEDDE81C06096');
        $this->addSql('ALTER TABLE booking RENAME INDEX user_id TO IDX_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking_transport ADD booking_ref VARCHAR(50) DEFAULT NULL, ADD payment_intent_id VARCHAR(100) DEFAULT NULL, ADD payment_method VARCHAR(20) DEFAULT NULL, CHANGE booking_id booking_id INT AUTO_INCREMENT NOT NULL, CHANGE offer_id offer_id INT DEFAULT NULL, CHANGE booking_date booking_date DATETIME NOT NULL, CHANGE status status VARCHAR(50) DEFAULT NULL, CHANGE pickup_datetime pickup_datetime DATETIME DEFAULT NULL, CHANGE dropoff_datetime dropoff_datetime DATETIME DEFAULT NULL, CHANGE travel_class travel_class VARCHAR(50) DEFAULT NULL, CHANGE cabin_bags cabin_bags INT DEFAULT NULL, CHANGE checked_bags checked_bags INT DEFAULT NULL, CHANGE pickup_location pickup_location VARCHAR(150) DEFAULT NULL, CHANGE dropoff_location dropoff_location VARCHAR(150) DEFAULT NULL, CHANGE customer_name customer_name VARCHAR(255) DEFAULT NULL, CHANGE customer_email customer_email VARCHAR(255) DEFAULT NULL, CHANGE customer_phone customer_phone VARCHAR(50) DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, ADD PRIMARY KEY (booking_id)');
        $this->addSql('ALTER TABLE booking_transport ADD CONSTRAINT FK_F599EA2D53C674EE FOREIGN KEY (offer_id) REFERENCES transport_details (transport_id)');
        $this->addSql('ALTER TABLE booking_transport ADD CONSTRAINT FK_F599EA2DA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('CREATE INDEX IDX_F599EA2D53C674EE ON booking_transport (offer_id)');
        $this->addSql('CREATE INDEX IDX_F599EA2DA76ED395 ON booking_transport (user_id)');
        $this->addSql('ALTER TABLE circuit DROP FOREIGN KEY FK_1325F3A661220EA6');
        $this->addSql('DROP INDEX idx_destination ON circuit');
        $this->addSql('DROP INDEX idx_type ON circuit');
        $this->addSql('ALTER TABLE circuit DROP latitude, DROP longitude, DROP popularite_score, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE type type VARCHAR(50) DEFAULT NULL, CHANGE status status VARCHAR(30) DEFAULT NULL, CHANGE difficulte difficulte VARCHAR(30) DEFAULT NULL, CHANGE depart depart VARCHAR(150) DEFAULT NULL, CHANGE actif actif TINYINT(1) NOT NULL, CHANGE is_custom is_custom TINYINT(1) NOT NULL, CHANGE is_ai_generated is_ai_generated TINYINT(1) NOT NULL, CHANGE source_type source_type VARCHAR(50) NOT NULL, CHANGE generated_context generated_context LONGTEXT DEFAULT NULL, CHANGE promo_prix promo_prix DOUBLE PRECISION DEFAULT NULL, CHANGE promo_start promo_start DATETIME DEFAULT NULL, CHANGE promo_end promo_end DATETIME DEFAULT NULL, CHANGE start_date start_date DATE DEFAULT NULL, CHANGE end_date end_date DATE DEFAULT NULL, CHANGE duree duree INT DEFAULT NULL, CHANGE budget budget DOUBLE PRECISION DEFAULT NULL, CHANGE image_url image_url LONGTEXT DEFAULT NULL, CHANGE prix_par_personne prix_par_personne DOUBLE PRECISION NOT NULL, CHANGE note_moyenne note_moyenne DOUBLE PRECISION DEFAULT NULL, CHANGE nb_avis nb_avis INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE circuit ADD CONSTRAINT FK_1325F3A661220EA6 FOREIGN KEY (creator_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE circuit RENAME INDEX fk_1325f3a661220ea6 TO IDX_1325F3A661220EA6');
        $this->addSql('ALTER TABLE circuit_avis DROP FOREIGN KEY circuit_avis_ibfk_1');
        $this->addSql('ALTER TABLE circuit_avis ADD CONSTRAINT FK_E669CD0DCDB85AD6 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit)');
        $this->addSql('ALTER TABLE circuit_avis RENAME INDEX id_circuit TO IDX_E669CD0DCDB85AD6');
        $this->addSql('ALTER TABLE circuit_avis RENAME INDEX user_id TO IDX_E669CD0DA76ED395');
        $this->addSql('ALTER TABLE circuit_reservation DROP FOREIGN KEY circuit_reservation_ibfk_1');
        $this->addSql('ALTER TABLE circuit_reservation DROP FOREIGN KEY circuit_reservation_ibfk_2');
        $this->addSql('ALTER TABLE circuit_reservation DROP meteo_info, DROP plan_b, CHANGE id_circuit id_circuit INT DEFAULT NULL, CHANGE nb_travelers nb_travelers INT DEFAULT NULL, CHANGE total_price total_price DOUBLE PRECISION DEFAULT NULL, CHANGE status status VARCHAR(30) DEFAULT NULL, CHANGE reserved_at reserved_at DATETIME NOT NULL, CHANGE date_depart date_depart DATE DEFAULT NULL, CHANGE pdf_path pdf_path VARCHAR(500) DEFAULT NULL, CHANGE qr_path qr_path VARCHAR(500) DEFAULT NULL, CHANGE nom_client nom_client VARCHAR(100) DEFAULT NULL, CHANGE email_client email_client VARCHAR(100) DEFAULT NULL, CHANGE telephone telephone VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE circuit_reservation ADD CONSTRAINT FK_A7A65D1ECDB85AD6 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit)');
        $this->addSql('ALTER TABLE circuit_reservation ADD CONSTRAINT FK_A7A65D1EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE circuit_reservation RENAME INDEX id_circuit TO IDX_A7A65D1ECDB85AD6');
        $this->addSql('ALTER TABLE circuit_reservation RENAME INDEX user_id TO IDX_A7A65D1EA76ED395');
        $this->addSql('ALTER TABLE favorite_activity ADD CONSTRAINT FK_62311ABA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE favorite_activity ADD CONSTRAINT FK_62311AB81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE favorite_activity RENAME INDEX idx_favact_user TO IDX_62311ABA76ED395');
        $this->addSql('ALTER TABLE favorite_activity RENAME INDEX idx_favact_activity TO IDX_62311AB81C06096');
        $this->addSql('ALTER TABLE favorite_circuit ADD CONSTRAINT FK_4E715DC8A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE favorite_circuit ADD CONSTRAINT FK_4E715DC8CF2182C8 FOREIGN KEY (circuit_id) REFERENCES circuit (id_circuit)');
        $this->addSql('ALTER TABLE favorite_circuit RENAME INDEX idx_favcirc_user TO IDX_4E715DC8A76ED395');
        $this->addSql('ALTER TABLE favorite_circuit RENAME INDEX idx_favcirc_circuit TO IDX_4E715DC8CF2182C8');
        $this->addSql('ALTER TABLE favorite_hebergement ADD CONSTRAINT FK_8B4098DFA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE favorite_hebergement ADD CONSTRAINT FK_8B4098DF23BB0F66 FOREIGN KEY (hebergement_id) REFERENCES hebergement (id_hebergement)');
        $this->addSql('ALTER TABLE favorite_hebergement RENAME INDEX idx_ed34f58ca76ed395 TO IDX_8B4098DFA76ED395');
        $this->addSql('ALTER TABLE favorite_hebergement RENAME INDEX idx_ed34f58c3d8cdc37 TO IDX_8B4098DF23BB0F66');
        $this->addSql('ALTER TABLE favorite_post ADD CONSTRAINT FK_B48C75B2A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE favorite_post ADD CONSTRAINT FK_B48C75B24B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE favorite_post RENAME INDEX idx_9ef68adda76ed395 TO IDX_B48C75B2A76ED395');
        $this->addSql('ALTER TABLE favorite_post RENAME INDEX idx_9ef68add5b1d5fd4 TO IDX_B48C75B24B89032C');
        $this->addSql('ALTER TABLE favorite_transport ADD CONSTRAINT FK_ACBBB4BCA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE favorite_transport ADD CONSTRAINT FK_ACBBB4BC9909C13F FOREIGN KEY (transport_id) REFERENCES transport_details (transport_id)');
        $this->addSql('ALTER TABLE favorite_transport RENAME INDEX idx_favtrans_user TO IDX_ACBBB4BCA76ED395');
        $this->addSql('ALTER TABLE favorite_transport RENAME INDEX idx_favtrans_transport TO IDX_ACBBB4BC9909C13F');
        $this->addSql('ALTER TABLE forum_comment CHANGE content content LONGTEXT NOT NULL, CHANGE is_pinned is_pinned TINYINT(1) NOT NULL, CHANGE score score INT DEFAULT 0 NOT NULL, CHANGE likes likes INT DEFAULT 0 NOT NULL, CHANGE dislikes dislikes INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE forum_comment RENAME INDEX post_id TO IDX_65B81F1D4B89032C');
        $this->addSql('ALTER TABLE forum_post CHANGE content content LONGTEXT NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE categorie categorie VARCHAR(50) DEFAULT NULL, CHANGE vues vues INT NOT NULL');
        $this->addSql('ALTER TABLE hebergement DROP FOREIGN KEY hebergement_ibfk_1');
        $this->addSql('DROP INDEX user_id ON hebergement');
        $this->addSql('ALTER TABLE hebergement CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE ville ville VARCHAR(50) NOT NULL, CHANGE adresse adresse VARCHAR(150) DEFAULT NULL, CHANGE prix_par_nuit prix_par_nuit DOUBLE PRECISION NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE disponible disponible TINYINT(1) NOT NULL, CHANGE image_path image_path VARCHAR(500) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE like_dislike ADD CONSTRAINT FK_ADB6A689A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE like_dislike RENAME INDEX idx_like_user TO IDX_ADB6A689A76ED395');
        $this->addSql('ALTER TABLE profil_voyageur CHANGE budget budget NUMERIC(10, 2) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE profil_voyageur RENAME INDEX user_id TO UNIQ_E2DB57F9A76ED395');
        $this->addSql('ALTER TABLE promo_code CHANGE type type VARCHAR(20) NOT NULL, CHANGE max_reduction max_reduction DOUBLE PRECISION DEFAULT NULL, CHANGE valid_from valid_from DATETIME DEFAULT NULL, CHANGE valid_until valid_until DATETIME DEFAULT NULL, CHANGE usage_limit usage_limit INT NOT NULL, CHANGE used_count used_count INT NOT NULL, CHANGE actif actif TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE promo_code RENAME INDEX code_unique TO UNIQ_3D8C939E77153098');
        $this->addSql('ALTER TABLE reservation_hebergement DROP FOREIGN KEY reservation_hebergement_ibfk_1');
        $this->addSql('ALTER TABLE reservation_hebergement CHANGE id_hebergement id_hebergement INT DEFAULT NULL, CHANGE telephone_client telephone_client VARCHAR(20) DEFAULT NULL, CHANGE nombre_personnes nombre_personnes INT NOT NULL, CHANGE telephone telephone VARCHAR(20) DEFAULT NULL, CHANGE statut statut VARCHAR(20) DEFAULT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE reservation_hebergement ADD CONSTRAINT FK_843E00C05040106B FOREIGN KEY (id_hebergement) REFERENCES hebergement (id_hebergement)');
        $this->addSql('ALTER TABLE reservation_hebergement RENAME INDEX id_hebergement TO IDX_843E00C05040106B');
        $this->addSql('ALTER TABLE reservation_hebergement RENAME INDEX user_id TO IDX_843E00C0A76ED395');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY review_ibfk_1');
        $this->addSql('ALTER TABLE review CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE author author VARCHAR(100) NOT NULL, CHANGE comment comment LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C681C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('CREATE INDEX IDX_794381C6A76ED395 ON review (user_id)');
        $this->addSql('ALTER TABLE review RENAME INDEX activity_id TO IDX_794381C681C06096');
        $this->addSql('DROP INDEX uq_transport_details_offer ON transport_details');
        $this->addSql('DROP INDEX idx_transport_route ON transport_details');
        $this->addSql('DROP INDEX idx_transport_departure ON transport_details');
        $this->addSql('ALTER TABLE transport_details CHANGE transport_type transport_type VARCHAR(50) DEFAULT NULL, CHANGE company_name company_name VARCHAR(150) DEFAULT NULL, CHANGE departure_city departure_city VARCHAR(100) DEFAULT NULL, CHANGE arrival_city arrival_city VARCHAR(100) DEFAULT NULL, CHANGE available_seats available_seats INT DEFAULT NULL, CHANGE price price NUMERIC(10, 2) DEFAULT NULL, CHANGE departure_station departure_station VARCHAR(100) DEFAULT NULL, CHANGE arrival_station arrival_station VARCHAR(100) DEFAULT NULL, CHANGE duration duration VARCHAR(50) DEFAULT NULL, CHANGE amenities amenities LONGTEXT DEFAULT NULL, CHANGE image_path image_path VARCHAR(500) DEFAULT NULL, CHANGE is_active is_active TINYINT(1) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_user_role ON user');
        $this->addSql('DROP INDEX idx_user_created_at ON user');
        $this->addSql('DROP INDEX idx_user_email ON user');
        $this->addSql('ALTER TABLE user DROP cover_photo_path, DROP auth_provider, DROP external_id, CHANGE email email VARCHAR(180) NOT NULL, CHANGE role role VARCHAR(50) DEFAULT NULL, CHANGE phone phone VARCHAR(20) DEFAULT NULL, CHANGE actif actif TINYINT(1) NOT NULL, CHANGE profile_picture_path profile_picture_path VARCHAR(500) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE user RENAME INDEX email TO UNIQ_8D93D649E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE car (car_id INT NOT NULL, brand VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, model VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, category VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, transmission VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, seats INT NOT NULL, doors INT NOT NULL, air_conditioning TINYINT(1) DEFAULT 1, fuel_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, is_active TINYINT(1) DEFAULT 1, image_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE car_rental_details (rental_id INT NOT NULL, offer_id INT NOT NULL, car_id INT NOT NULL, unlimited_mileage TINYINT(1) DEFAULT 0, deposit_amount NUMERIC(10, 2) DEFAULT \'NULL\', available_quantity INT DEFAULT 1) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE centre_interet (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, icone VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE chatbot_faq (id INT AUTO_INCREMENT NOT NULL, question VARCHAR(500) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reponse TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, categorie VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\'\'GÃ©nÃ©ral\'\'\' COLLATE `utf8mb4_general_ci`, nombre_clics INT DEFAULT 0, actif TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'NULL\', INDEX idx_categorie (categorie), INDEX idx_actif (actif), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE circuit_destination (id INT AUTO_INCREMENT NOT NULL, id_circuit INT DEFAULT NULL, nom VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, pays VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, ordre INT DEFAULT 1, INDEX id_circuit (id_circuit), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE circuit_interet (id_circuit INT NOT NULL, id_interet INT NOT NULL, INDEX id_interet (id_interet), INDEX IDX_945C3940CDB85AD6 (id_circuit), PRIMARY KEY(id_circuit, id_interet)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE circuit_personnalise (id_perso INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, destination VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_depart DATE DEFAULT \'NULL\', duree INT DEFAULT 1, budget_min DOUBLE PRECISION DEFAULT \'0\', budget_max DOUBLE PRECISION DEFAULT \'0\', style_voyage VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, centres_interet TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, niveau_fatigue INT DEFAULT 1, etape INT DEFAULT 1, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'BROUILLON\'\'\' COLLATE `utf8mb4_general_ci`, meteo_info TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, plan_b TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX user_id (user_id), PRIMARY KEY(id_perso)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE circuit_review (id INT AUTO_INCREMENT NOT NULL, id_circuit INT NOT NULL, user_id INT DEFAULT NULL, comment TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, rating INT DEFAULT NULL, helpful_count INT DEFAULT 0, verified_purchase TINYINT(1) DEFAULT 0, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX id_circuit (id_circuit), UNIQUE INDEX uq_user_circuit (user_id, id_circuit), INDEX IDX_7C80B3A3A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE forum_reaction (id INT AUTO_INCREMENT NOT NULL, post_id INT NOT NULL, author VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'\'\'LIKE\'\'\' NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'LIKE | DISLIKE | LOVE | WOW\', UNIQUE INDEX uq_reaction (post_id, author), INDEX IDX_83248A104B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE game_reward (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT 0 NOT NULL, user_name VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, reward_type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reward_label VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, used TINYINT(1) DEFAULT 0 NOT NULL, INDEX idx_user_id (user_id), INDEX idx_reward_type (reward_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jour_circuit (id_jour INT AUTO_INCREMENT NOT NULL, id_circuit INT NOT NULL, numero_jour INT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, activites TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, hebergement VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, transport VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, budget_jour DOUBLE PRECISION DEFAULT \'0\', latitude NUMERIC(10, 7) DEFAULT \'NULL\', longitude NUMERIC(10, 7) DEFAULT \'NULL\', INDEX id_circuit (id_circuit), PRIMARY KEY(id_jour)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification (notif_id INT NOT NULL, user_id INT NOT NULL, type VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT \'\'\'SYSTEM\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci`, title VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, message TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, is_read TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, related_entity_id INT DEFAULT NULL, related_entity_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE offer (offer_id INT NOT NULL, title VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, offer_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, base_price NUMERIC(10, 2) NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\', updated_at DATETIME DEFAULT \'current_timestamp()\', is_active TINYINT(1) DEFAULT 1 NOT NULL, from_city VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, to_city VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, eco_score INT DEFAULT 50 NOT NULL, reliability_score INT DEFAULT 75 NOT NULL, image_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'Relative path to offer image, e.g. uploads/offers/offer_42_1234567890.jpg\', PRIMARY KEY(offer_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE password_reset_tokens (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expiration_date DATETIME NOT NULL, used TINYINT(1) DEFAULT 0, created_at DATETIME DEFAULT \'current_timestamp()\', INDEX idx_token (token), INDEX idx_token_expiration (expiration_date), UNIQUE INDEX token (token), INDEX user_id (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, booking_id INT NOT NULL, amount NUMERIC(10, 2) NOT NULL, method VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, payment_date DATE DEFAULT \'NULL\', status VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'PENDING\'\'\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX booking_id (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE place (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, latitude NUMERIC(10, 7) DEFAULT \'NULL\' COMMENT \'Latitude GPS du lieu\', longitude NUMERIC(10, 7) DEFAULT \'NULL\' COMMENT \'Longitude GPS du lieu\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE price_alert (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, origin VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, destination VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, target_price NUMERIC(10, 2) DEFAULT \'NULL\', target_date DATE DEFAULT \'NULL\', email_notified TINYINT(1) DEFAULT 0, last_price NUMERIC(10, 2) DEFAULT \'NULL\', status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'\'\'ACTIVE\'\'\' COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'NULL\', INDEX idx_route_alerts (origin, destination), INDEX idx_user_alerts (user_id, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE price_cache (id INT AUTO_INCREMENT NOT NULL, cache_key VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, provider VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, search_type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, request_params LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, response_data LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_expires (expires_at), UNIQUE INDEX cache_key (cache_key), INDEX idx_cache_key (cache_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE price_provider (id INT AUTO_INCREMENT NOT NULL, provider_code VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, provider_name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, is_active TINYINT(1) DEFAULT 1, priority INT DEFAULT 10, api_endpoint VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, credentials LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, rate_limit INT DEFAULT 100, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX provider_code (provider_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE price_search_history (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, search_type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'flight, hotel, car\', origin VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'IATA code or city\', destination VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, check_in DATE DEFAULT \'NULL\', check_out DATE DEFAULT \'NULL\', adults INT DEFAULT 1, children INT DEFAULT 0, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_user_search (user_id, created_at), INDEX idx_search_type (search_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE taxi_details (taxi_id INT AUTO_INCREMENT NOT NULL, offer_id INT NOT NULL, vehicle_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, max_passengers INT NOT NULL, air_conditioned TINYINT(1) DEFAULT 1 NOT NULL, luggage_included TINYINT(1) DEFAULT 1 NOT NULL, baby_seat TINYINT(1) DEFAULT 0 NOT NULL, pets_allowed TINYINT(1) DEFAULT 0 NOT NULL, price_per_km NUMERIC(10, 2) NOT NULL, UNIQUE INDEX uq_taxi_details_offer (offer_id), PRIMARY KEY(taxi_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE circuit_destination ADD CONSTRAINT circuit_destination_ibfk_1 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_interet ADD CONSTRAINT circuit_interet_ibfk_1 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_interet ADD CONSTRAINT circuit_interet_ibfk_2 FOREIGN KEY (id_interet) REFERENCES centre_interet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_personnalise ADD CONSTRAINT circuit_personnalise_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_review ADD CONSTRAINT circuit_review_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_review ADD CONSTRAINT circuit_review_ibfk_1 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_reaction ADD CONSTRAINT fk_reaction_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jour_circuit ADD CONSTRAINT jour_circuit_ibfk_1 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT password_reset_tokens_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT payment_ibfk_1 FOREIGN KEY (booking_id) REFERENCES booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taxi_details ADD CONSTRAINT fk_taxi_offer FOREIGN KEY (offer_id) REFERENCES offer (offer_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity ADD place_id INT DEFAULT NULL, ADD user_id INT DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE price price NUMERIC(10, 2) NOT NULL, CHANGE duration duration VARCHAR(50) DEFAULT \'NULL\', CHANGE date date DATE DEFAULT \'NULL\', CHANGE image image VARCHAR(255) DEFAULT \'NULL\', CHANGE lieu lieu VARCHAR(100) DEFAULT \'NULL\', CHANGE actif actif TINYINT(1) DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT activity_ibfk_1 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX place_id ON activity (place_id)');
        $this->addSql('ALTER TABLE avis_hebergement CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE avis_hebergement RENAME INDEX idx_17bb90335040106b TO id_hebergement');
        $this->addSql('ALTER TABLE avis_hebergement RENAME INDEX idx_17bb9033a76ed395 TO user_id');
        $this->addSql('ALTER TABLE avis_transport DROP FOREIGN KEY FK_C0FE3EEF53C674EE');
        $this->addSql('ALTER TABLE avis_transport DROP FOREIGN KEY FK_C0FE3EEFA76ED395');
        $this->addSql('DROP INDEX IDX_C0FE3EEF53C674EE ON avis_transport');
        $this->addSql('DROP INDEX IDX_C0FE3EEFA76ED395 ON avis_transport');
        $this->addSql('ALTER TABLE avis_transport CHANGE rating rating INT DEFAULT 5 NOT NULL, CHANGE comment comment TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE81C06096');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking ADD payment_status VARCHAR(20) DEFAULT \'\'\'EN ATTENTE\'\'\' COMMENT \'Statut du paiement : EN ATTENTE / PAYÃ‰ / Ã‰CHOUÃ‰\', ADD payment_ref VARCHAR(60) DEFAULT \'NULL\' COMMENT \'RÃ©fÃ©rence Stripe : ch_test_XXXX\', CHANGE activity_id activity_id INT NOT NULL, CHANGE client_phone client_phone VARCHAR(50) DEFAULT \'NULL\', CHANGE status status VARCHAR(50) DEFAULT \'\'\'PENDING\'\'\', CHANGE payment_intent_id payment_intent_id VARCHAR(255) DEFAULT \'NULL\', CHANGE payment_method payment_method VARCHAR(50) DEFAULT \'NULL\', CHANGE booking_reference booking_reference VARCHAR(100) DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT booking_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT booking_ibfk_1 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_booking_payment_status ON booking (payment_status)');
        $this->addSql('CREATE INDEX idx_booking_status ON booking (status)');
        $this->addSql('ALTER TABLE booking RENAME INDEX idx_e00ceddea76ed395 TO user_id');
        $this->addSql('ALTER TABLE booking RENAME INDEX idx_e00cedde81c06096 TO activity_id');
        $this->addSql('ALTER TABLE booking_transport MODIFY booking_id INT NOT NULL');
        $this->addSql('ALTER TABLE booking_transport DROP FOREIGN KEY FK_F599EA2D53C674EE');
        $this->addSql('ALTER TABLE booking_transport DROP FOREIGN KEY FK_F599EA2DA76ED395');
        $this->addSql('DROP INDEX IDX_F599EA2D53C674EE ON booking_transport');
        $this->addSql('DROP INDEX IDX_F599EA2DA76ED395 ON booking_transport');
        $this->addSql('DROP INDEX `primary` ON booking_transport');
        $this->addSql('ALTER TABLE booking_transport DROP booking_ref, DROP payment_intent_id, DROP payment_method, CHANGE booking_id booking_id INT NOT NULL, CHANGE offer_id offer_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE booking_date booking_date DATETIME DEFAULT \'current_timestamp()\', CHANGE status status VARCHAR(50) DEFAULT \'NULL\', CHANGE pickup_datetime pickup_datetime DATETIME DEFAULT \'NULL\', CHANGE dropoff_datetime dropoff_datetime DATETIME DEFAULT \'NULL\', CHANGE travel_class travel_class VARCHAR(50) DEFAULT \'NULL\', CHANGE cabin_bags cabin_bags INT DEFAULT 0, CHANGE checked_bags checked_bags INT DEFAULT 0, CHANGE pickup_location pickup_location VARCHAR(150) DEFAULT \'NULL\', CHANGE dropoff_location dropoff_location VARCHAR(150) DEFAULT \'NULL\', CHANGE customer_name customer_name VARCHAR(255) DEFAULT \'NULL\', CHANGE customer_email customer_email VARCHAR(255) DEFAULT \'NULL\', CHANGE customer_phone customer_phone VARCHAR(50) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE circuit DROP FOREIGN KEY FK_1325F3A661220EA6');
        $this->addSql('ALTER TABLE circuit ADD latitude NUMERIC(10, 7) DEFAULT \'NULL\', ADD longitude NUMERIC(10, 7) DEFAULT \'NULL\', ADD popularite_score INT DEFAULT 50, CHANGE description description TEXT DEFAULT NULL, CHANGE type type VARCHAR(50) DEFAULT \'\'\'Aventure\'\'\', CHANGE status status VARCHAR(30) DEFAULT \'\'\'actif\'\'\', CHANGE start_date start_date DATE DEFAULT \'NULL\', CHANGE end_date end_date DATE DEFAULT \'NULL\', CHANGE duree duree INT DEFAULT 1, CHANGE budget budget DOUBLE PRECISION DEFAULT \'0\', CHANGE image_url image_url TEXT DEFAULT NULL, CHANGE prix_par_personne prix_par_personne DOUBLE PRECISION DEFAULT \'0\', CHANGE note_moyenne note_moyenne DOUBLE PRECISION DEFAULT \'0\', CHANGE nb_avis nb_avis INT DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE difficulte difficulte VARCHAR(30) DEFAULT \'NULL\', CHANGE depart depart VARCHAR(150) DEFAULT \'NULL\', CHANGE actif actif TINYINT(1) DEFAULT 1, CHANGE is_custom is_custom TINYINT(1) DEFAULT 0, CHANGE is_ai_generated is_ai_generated TINYINT(1) DEFAULT 0, CHANGE source_type source_type VARCHAR(50) DEFAULT \'\'\'admin\'\'\', CHANGE generated_context generated_context TEXT DEFAULT NULL, CHANGE promo_prix promo_prix DOUBLE PRECISION DEFAULT \'NULL\', CHANGE promo_start promo_start DATETIME DEFAULT \'NULL\', CHANGE promo_end promo_end DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE circuit ADD CONSTRAINT FK_1325F3A661220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX idx_destination ON circuit (destination)');
        $this->addSql('CREATE INDEX idx_type ON circuit (type)');
        $this->addSql('ALTER TABLE circuit RENAME INDEX idx_1325f3a661220ea6 TO FK_1325F3A661220EA6');
        $this->addSql('ALTER TABLE circuit_avis DROP FOREIGN KEY FK_E669CD0DCDB85AD6');
        $this->addSql('ALTER TABLE circuit_avis ADD CONSTRAINT circuit_avis_ibfk_1 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_avis RENAME INDEX idx_e669cd0dcdb85ad6 TO id_circuit');
        $this->addSql('ALTER TABLE circuit_avis RENAME INDEX idx_e669cd0da76ed395 TO user_id');
        $this->addSql('ALTER TABLE circuit_reservation DROP FOREIGN KEY FK_A7A65D1ECDB85AD6');
        $this->addSql('ALTER TABLE circuit_reservation DROP FOREIGN KEY FK_A7A65D1EA76ED395');
        $this->addSql('ALTER TABLE circuit_reservation ADD meteo_info TEXT DEFAULT NULL, ADD plan_b TEXT DEFAULT NULL, CHANGE id_circuit id_circuit INT NOT NULL, CHANGE nb_travelers nb_travelers INT DEFAULT 1, CHANGE total_price total_price DOUBLE PRECISION DEFAULT \'0\', CHANGE status status VARCHAR(30) DEFAULT \'\'\'CONFIRME\'\'\', CHANGE reserved_at reserved_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE date_depart date_depart DATE DEFAULT \'NULL\', CHANGE pdf_path pdf_path VARCHAR(500) DEFAULT \'NULL\', CHANGE qr_path qr_path VARCHAR(500) DEFAULT \'NULL\', CHANGE nom_client nom_client VARCHAR(100) DEFAULT \'NULL\', CHANGE email_client email_client VARCHAR(100) DEFAULT \'NULL\', CHANGE telephone telephone VARCHAR(20) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE circuit_reservation ADD CONSTRAINT circuit_reservation_ibfk_1 FOREIGN KEY (id_circuit) REFERENCES circuit (id_circuit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_reservation ADD CONSTRAINT circuit_reservation_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE circuit_reservation RENAME INDEX idx_a7a65d1ecdb85ad6 TO id_circuit');
        $this->addSql('ALTER TABLE circuit_reservation RENAME INDEX idx_a7a65d1ea76ed395 TO user_id');
        $this->addSql('ALTER TABLE favorite_activity DROP FOREIGN KEY FK_62311ABA76ED395');
        $this->addSql('ALTER TABLE favorite_activity DROP FOREIGN KEY FK_62311AB81C06096');
        $this->addSql('ALTER TABLE favorite_activity RENAME INDEX idx_62311aba76ed395 TO IDX_FAVACT_USER');
        $this->addSql('ALTER TABLE favorite_activity RENAME INDEX idx_62311ab81c06096 TO IDX_FAVACT_ACTIVITY');
        $this->addSql('ALTER TABLE favorite_circuit DROP FOREIGN KEY FK_4E715DC8A76ED395');
        $this->addSql('ALTER TABLE favorite_circuit DROP FOREIGN KEY FK_4E715DC8CF2182C8');
        $this->addSql('ALTER TABLE favorite_circuit RENAME INDEX idx_4e715dc8cf2182c8 TO IDX_FAVCIRC_CIRCUIT');
        $this->addSql('ALTER TABLE favorite_circuit RENAME INDEX idx_4e715dc8a76ed395 TO IDX_FAVCIRC_USER');
        $this->addSql('ALTER TABLE favorite_hebergement DROP FOREIGN KEY FK_8B4098DFA76ED395');
        $this->addSql('ALTER TABLE favorite_hebergement DROP FOREIGN KEY FK_8B4098DF23BB0F66');
        $this->addSql('ALTER TABLE favorite_hebergement RENAME INDEX idx_8b4098dfa76ed395 TO IDX_ED34F58CA76ED395');
        $this->addSql('ALTER TABLE favorite_hebergement RENAME INDEX idx_8b4098df23bb0f66 TO IDX_ED34F58C3D8CDC37');
        $this->addSql('ALTER TABLE favorite_post DROP FOREIGN KEY FK_B48C75B2A76ED395');
        $this->addSql('ALTER TABLE favorite_post DROP FOREIGN KEY FK_B48C75B24B89032C');
        $this->addSql('ALTER TABLE favorite_post RENAME INDEX idx_b48c75b24b89032c TO IDX_9EF68ADD5B1D5FD4');
        $this->addSql('ALTER TABLE favorite_post RENAME INDEX idx_b48c75b2a76ed395 TO IDX_9EF68ADDA76ED395');
        $this->addSql('ALTER TABLE favorite_transport DROP FOREIGN KEY FK_ACBBB4BCA76ED395');
        $this->addSql('ALTER TABLE favorite_transport DROP FOREIGN KEY FK_ACBBB4BC9909C13F');
        $this->addSql('ALTER TABLE favorite_transport RENAME INDEX idx_acbbb4bca76ed395 TO IDX_FAVTRANS_USER');
        $this->addSql('ALTER TABLE favorite_transport RENAME INDEX idx_acbbb4bc9909c13f TO IDX_FAVTRANS_TRANSPORT');
        $this->addSql('ALTER TABLE forum_comment CHANGE content content TEXT NOT NULL, CHANGE score score INT DEFAULT 0, CHANGE likes likes INT DEFAULT 0, CHANGE dislikes dislikes INT DEFAULT 0, CHANGE is_pinned is_pinned TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE forum_comment RENAME INDEX idx_65b81f1d4b89032c TO post_id');
        $this->addSql('ALTER TABLE forum_post CHANGE content content TEXT NOT NULL, CHANGE categorie categorie VARCHAR(50) DEFAULT \'NULL\', CHANGE status status VARCHAR(20) DEFAULT \'\'\'APPROVED\'\'\' NOT NULL COMMENT \'APPROVED | PENDING | REJECTED\', CHANGE vues vues INT DEFAULT 0');
        $this->addSql('ALTER TABLE hebergement CHANGE nom nom VARCHAR(100) DEFAULT \'NULL\', CHANGE ville ville VARCHAR(50) DEFAULT \'NULL\', CHANGE type type VARCHAR(50) DEFAULT \'NULL\', CHANGE prix_par_nuit prix_par_nuit DOUBLE PRECISION DEFAULT \'NULL\', CHANGE image_path image_path VARCHAR(500) DEFAULT \'NULL\', CHANGE description description TEXT DEFAULT NULL, CHANGE adresse adresse VARCHAR(150) DEFAULT \'NULL\', CHANGE disponible disponible TINYINT(1) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE hebergement ADD CONSTRAINT hebergement_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX user_id ON hebergement (user_id)');
        $this->addSql('ALTER TABLE like_dislike DROP FOREIGN KEY FK_ADB6A689A76ED395');
        $this->addSql('ALTER TABLE like_dislike RENAME INDEX idx_adb6a689a76ed395 TO IDX_like_user');
        $this->addSql('ALTER TABLE profil_voyageur CHANGE budget budget NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('ALTER TABLE profil_voyageur RENAME INDEX uniq_e2db57f9a76ed395 TO user_id');
        $this->addSql('ALTER TABLE promo_code CHANGE type type VARCHAR(20) DEFAULT \'\'\'percentage\'\'\' NOT NULL, CHANGE max_reduction max_reduction DOUBLE PRECISION DEFAULT \'NULL\', CHANGE valid_from valid_from DATETIME DEFAULT \'NULL\', CHANGE valid_until valid_until DATETIME DEFAULT \'NULL\', CHANGE usage_limit usage_limit INT DEFAULT 0 NOT NULL, CHANGE used_count used_count INT DEFAULT 0 NOT NULL, CHANGE actif actif TINYINT(1) DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE promo_code RENAME INDEX uniq_3d8c939e77153098 TO code_unique');
        $this->addSql('ALTER TABLE reservation_hebergement DROP FOREIGN KEY FK_843E00C05040106B');
        $this->addSql('ALTER TABLE reservation_hebergement CHANGE id_hebergement id_hebergement INT NOT NULL, CHANGE telephone telephone VARCHAR(20) DEFAULT \'NULL\', CHANGE telephone_client telephone_client VARCHAR(20) DEFAULT \'NULL\', CHANGE nombre_personnes nombre_personnes INT DEFAULT 1, CHANGE statut statut VARCHAR(20) DEFAULT \'\'\'En attente\'\'\', CHANGE date_creation date_creation DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('ALTER TABLE reservation_hebergement ADD CONSTRAINT reservation_hebergement_ibfk_1 FOREIGN KEY (id_hebergement) REFERENCES hebergement (id_hebergement) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation_hebergement RENAME INDEX idx_843e00c0a76ed395 TO user_id');
        $this->addSql('ALTER TABLE reservation_hebergement RENAME INDEX idx_843e00c05040106b TO id_hebergement');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C681C06096');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6A76ED395');
        $this->addSql('DROP INDEX IDX_794381C6A76ED395 ON review');
        $this->addSql('ALTER TABLE review CHANGE activity_id activity_id INT NOT NULL, CHANGE author author VARCHAR(100) NOT NULL COLLATE `utf8mb4_general_ci`, CHANGE comment comment TEXT DEFAULT NULL COLLATE `utf8mb4_general_ci`');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT review_ibfk_1 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review RENAME INDEX idx_794381c681c06096 TO activity_id');
        $this->addSql('ALTER TABLE transport_details CHANGE transport_type transport_type VARCHAR(50) DEFAULT \'NULL\', CHANGE company_name company_name VARCHAR(150) DEFAULT \'NULL\', CHANGE departure_city departure_city VARCHAR(100) DEFAULT \'NULL\', CHANGE arrival_city arrival_city VARCHAR(100) DEFAULT \'NULL\', CHANGE available_seats available_seats INT DEFAULT 0, CHANGE price price NUMERIC(10, 2) DEFAULT \'NULL\', CHANGE departure_station departure_station VARCHAR(100) DEFAULT \'NULL\', CHANGE arrival_station arrival_station VARCHAR(100) DEFAULT \'NULL\', CHANGE duration duration VARCHAR(50) DEFAULT \'NULL\', CHANGE amenities amenities TEXT DEFAULT NULL, CHANGE image_path image_path VARCHAR(500) DEFAULT \'NULL\', CHANGE is_active is_active TINYINT(1) DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE transport_details ADD CONSTRAINT fk_transport_offer FOREIGN KEY (offer_id) REFERENCES offer (offer_id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX uq_transport_details_offer ON transport_details (offer_id)');
        $this->addSql('CREATE INDEX idx_transport_route ON transport_details (departure_city, arrival_city)');
        $this->addSql('CREATE INDEX idx_transport_departure ON transport_details (departure_datetime)');
        $this->addSql('ALTER TABLE `user` ADD cover_photo_path VARCHAR(500) DEFAULT \'NULL\', ADD auth_provider VARCHAR(20) DEFAULT \'\'\'LOCAL\'\'\' NOT NULL, ADD external_id VARCHAR(255) DEFAULT \'NULL\', CHANGE email email VARCHAR(255) NOT NULL, CHANGE role role VARCHAR(50) DEFAULT \'NULL\', CHANGE phone phone VARCHAR(20) NOT NULL, CHANGE profile_picture_path profile_picture_path VARCHAR(500) DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\', CHANGE actif actif TINYINT(1) DEFAULT 1');
        $this->addSql('CREATE INDEX idx_user_role ON `user` (role)');
        $this->addSql('CREATE INDEX idx_user_created_at ON `user` (created_at)');
        $this->addSql('CREATE INDEX idx_user_email ON `user` (email)');
        $this->addSql('ALTER TABLE `user` RENAME INDEX uniq_8d93d649e7927c74 TO email');
    }
}
