<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OTSpWFZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OTSpWFZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OTSpWFZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'bookingRepository' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
            'circuitAvisRepository' => ['privates', 'App\\Repository\\CircuitAvisRepository', 'getCircuitAvisRepositoryService', true],
            'circuitRepository' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
            'reservationCircuitRepository' => ['privates', 'App\\Repository\\ReservationCircuitRepository', 'getReservationCircuitRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'bookingRepository' => 'App\\Repository\\BookingRepository',
            'circuitAvisRepository' => 'App\\Repository\\CircuitAvisRepository',
            'circuitRepository' => 'App\\Repository\\CircuitRepository',
            'reservationCircuitRepository' => 'App\\Repository\\ReservationCircuitRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
        ]);
    }
}
