<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hajk3CgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hajk3Cg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
        ], [
            'em' => '?',
            'hasher' => '?',
            'httpClient' => '?',
        ]);

        if (isset($container->privates['.service_locator.hajk3Cg'])) {
            return $container->privates['.service_locator.hajk3Cg'];
        }

        return $container->privates['.service_locator.hajk3Cg'] = $instance;
    }
}
