<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U7x_MOSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U7x.MOS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avis' => ['privates', '.errored..service_locator.U7x.MOS.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.U7x.MOS": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'avis' => 'App\\Entity\\Avis',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.U7x.MOS'])) {
            return $container->privates['.service_locator.U7x.MOS'];
        }

        return $container->privates['.service_locator.U7x.MOS'] = $instance;
    }
}
