<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I3l8xk8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I3l8xk8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\ReservationCircuitRepository', 'getReservationCircuitRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\ReservationCircuitRepository',
        ]);

        if (isset($container->privates['.service_locator.I3l8xk8'])) {
            return $container->privates['.service_locator.I3l8xk8'];
        }

        return $container->privates['.service_locator.I3l8xk8'] = $instance;
    }
}
