<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ThVCIC1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.thVCIC1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepo' => ['privates', 'App\\Repository\\ForumCommentRepository', 'getForumCommentRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\ForumPostRepository', 'getForumPostRepositoryService', true],
        ], [
            'commentRepo' => 'App\\Repository\\ForumCommentRepository',
            'paginator' => '?',
            'repo' => 'App\\Repository\\ForumPostRepository',
        ]);

        if (isset($container->privates['.service_locator.thVCIC1'])) {
            return $container->privates['.service_locator.thVCIC1'];
        }

        return $container->privates['.service_locator.thVCIC1'] = $instance;
    }
}
