<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TCiwQaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T_CiwQa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache' => ['services', 'cache.app', 'getCache_AppService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\FAQRepository', 'getFAQRepositoryService', true],
        ], [
            'cache' => '?',
            'em' => '?',
            'repo' => 'App\\Repository\\FAQRepository',
        ]);

        if (isset($container->privates['.service_locator.T_CiwQa'])) {
            return $container->privates['.service_locator.T_CiwQa'];
        }

        return $container->privates['.service_locator.T_CiwQa'] = $instance;
    }
}
