<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q7EM4xsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q7EM4xs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\TransportAvisRepository', 'getTransportAvisRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\TransportAvisRepository',
        ]);

        if (isset($container->privates['.service_locator.Q7EM4xs'])) {
            return $container->privates['.service_locator.Q7EM4xs'];
        }

        return $container->privates['.service_locator.Q7EM4xs'] = $instance;
    }
}
