<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2YSGhrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C2YSGhr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
            'resRepo' => ['privates', 'App\\Repository\\ReservationCircuitRepository', 'getReservationCircuitRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\CircuitRepository',
            'resRepo' => 'App\\Repository\\ReservationCircuitRepository',
        ]);

        if (isset($container->privates['.service_locator.C2YSGhr'])) {
            return $container->privates['.service_locator.C2YSGhr'];
        }

        return $container->privates['.service_locator.C2YSGhr'] = $instance;
    }
}
