<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Buy7oY8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.buy7oY8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\AvisRepository',
        ]);

        if (isset($container->privates['.service_locator.buy7oY8'])) {
            return $container->privates['.service_locator.buy7oY8'];
        }

        return $container->privates['.service_locator.buy7oY8'] = $instance;
    }
}
