<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ChatbotController' shared autowired service.
     *
     * @return \App\Controller\ChatbotController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ChatbotController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ChatbotService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NLPService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OpenRouterService.php';

        $container->services['App\\Controller\\ChatbotController'] = $instance = new \App\Controller\ChatbotController(new \App\Service\ChatbotService(($container->privates['App\\Service\\OpenAIService'] ?? $container->load('getOpenAIServiceService')), new \App\Service\NLPService(), ($container->privates['App\\Repository\\FAQRepository'] ?? $container->load('getFAQRepositoryService')), ($container->privates['App\\Repository\\CircuitRepository'] ?? $container->load('getCircuitRepositoryService')), ($container->privates['App\\Service\\HuggingFaceService'] ?? $container->load('getHuggingFaceServiceService')), ($container->services['cache.app'] ?? self::getCache_AppService($container))), ($container->privates['App\\Service\\TravelPreparationAssistantService'] ?? $container->load('getTravelPreparationAssistantServiceService')), new \App\Service\OpenRouterService($container->getEnv('OPENROUTER_API_KEY'), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container))), ($container->privates['App\\Repository\\HebergementRepository'] ?? $container->load('getHebergementRepositoryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ChatbotController', $container));

        return $instance;
    }
}
