<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircuitControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CircuitController' shared autowired service.
     *
     * @return \App\Controller\CircuitController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CircuitController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'MapboxService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CircuitPdfService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'PaymentService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'WeatherApiService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'SherpaService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ContentModerationService.php';

        $container->services['App\\Controller\\CircuitController'] = $instance = new \App\Controller\CircuitController(($container->privates['App\\Service\\Api\\PaymentService'] ??= new \App\Service\Api\PaymentService()), ($container->privates['App\\Service\\ReceiptService'] ?? $container->load('getReceiptServiceService')), ($container->privates['App\\Service\\Api\\WeatherApiService'] ??= new \App\Service\Api\WeatherApiService()), new \App\Service\Api\MapboxService(), ($container->privates['App\\Service\\Api\\SherpaService'] ??= new \App\Service\Api\SherpaService()), ($container->privates['App\\Service\\Api\\MailerService'] ?? $container->load('getMailerServiceService')), new \App\Service\CircuitPdfService(($container->privates['twig'] ?? self::getTwigService($container))), ($container->privates['App\\Service\\SentimentService'] ?? $container->load('getSentimentServiceService')), ($container->privates['App\\Service\\ContentModerationService'] ??= new \App\Service\ContentModerationService($container->getEnv('OPENAI_API_KEY'))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CircuitController', $container));

        return $instance;
    }
}
