<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollationAnalyzerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Configuration\CollationAnalyzer' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\CollationAnalyzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'AnalyzerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Configuration'.\DIRECTORY_SEPARATOR.'CollationAnalyzer.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'];
        }
        $b = ($container->privates['AhmedBhs\\DoctrineDoctor\\Utils\\DatabasePlatformDetector'] ?? $container->load('getDatabasePlatformDetectorService'));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'];
        }

        $instance = new \AhmedBhs\DoctrineDoctor\Analyzer\Configuration\CollationAnalyzer($a, ($container->privates['AhmedBhs\\DoctrineDoctor\\Factory\\SuggestionFactory'] ?? $container->load('getSuggestionFactoryService')), $b, ($container->privates['logger'] ?? self::getLoggerService($container)));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'];
        }

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Configuration\\CollationAnalyzer'] = $instance;
    }
}
