<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExerciseHtmlPurifier_ActivityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'exercise_html_purifier.activity' shared service.
     *
     * @return \HTMLPurifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ezyang'.\DIRECTORY_SEPARATOR.'htmlpurifier'.\DIRECTORY_SEPARATOR.'library'.\DIRECTORY_SEPARATOR.'HTMLPurifier.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ezyang'.\DIRECTORY_SEPARATOR.'htmlpurifier'.\DIRECTORY_SEPARATOR.'library'.\DIRECTORY_SEPARATOR.'HTMLPurifier'.\DIRECTORY_SEPARATOR.'Config.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'exercise'.\DIRECTORY_SEPARATOR.'htmlpurifier-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HTMLPurifierConfigFactory.php';

        return $container->privates['exercise_html_purifier.activity'] = new \HTMLPurifier(\Exercise\HTMLPurifierBundle\HTMLPurifierConfigFactory::create('activity', ['HTML' => ['Allowed' => 'p,br,strong,em,b,i,u,a[href],ul,ol,li,h1,h2,h3,h4,h5,h6,img[src|alt|title],span'], 'CSS' => ['AllowedProperties' => 'color,font-size,font-weight,text-align'], 'URI' => ['AllowedSchemes' => 'http,https,mailto']], ($container->privates['exercise_html_purifier.config.default'] ?? $container->load('getExerciseHtmlPurifier_Config_DefaultService')), [], [], [], []));
    }
}
