<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlightApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\FlightApiService' shared autowired service.
     *
     * @return \App\Service\Api\FlightApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'FlightApiService.php';

        return $container->privates['App\\Service\\Api\\FlightApiService'] = new \App\Service\Api\FlightApiService();
    }
}
