<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallFontCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Mopa\Bundle\BootstrapBundle\Command\InstallFontCommand' shared service.
     *
     * @return \Mopa\Bundle\BootstrapBundle\Command\InstallFontCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mopa'.\DIRECTORY_SEPARATOR.'bootstrap-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'InstallFontCommand.php';

        $container->services['Mopa\\Bundle\\BootstrapBundle\\Command\\InstallFontCommand'] = $instance = new \Mopa\Bundle\BootstrapBundle\Command\InstallFontCommand(($container->services['kernel'] ?? $container->get('kernel', 1)), 'glyphicons');

        $instance->setName('mopa:bootstrap:install:font');

        return $instance;
    }
}
