<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpGaufrette_FilesystemMapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'knp_gaufrette.filesystem_map' shared service.
     *
     * @return \Knp\Bundle\GaufretteBundle\FilesystemMap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'gaufrette'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Gaufrette'.\DIRECTORY_SEPARATOR.'FilesystemMapInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-gaufrette-bundle'.\DIRECTORY_SEPARATOR.'FilesystemMap.php';

        return $container->services['knp_gaufrette.filesystem_map'] = new \Knp\Bundle\GaufretteBundle\FilesystemMap(['activity_fs' => ($container->services['ActivityFileSystem'] ?? $container->load('getActivityFileSystemService')), 'circuit_fs' => ($container->services['CircuitFileSystem'] ?? $container->load('getCircuitFileSystemService'))]);
    }
}
