<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecaptchaLoginAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\RecaptchaLoginAuthenticator' shared autowired service.
     *
     * @return \App\Security\RecaptchaLoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authenticator'.\DIRECTORY_SEPARATOR.'AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authenticator'.\DIRECTORY_SEPARATOR.'AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'EntryPoint'.\DIRECTORY_SEPARATOR.'AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authenticator'.\DIRECTORY_SEPARATOR.'InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authenticator'.\DIRECTORY_SEPARATOR.'AbstractLoginFormAuthenticator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'RecaptchaLoginAuthenticator.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\Security\\RecaptchaLoginAuthenticator'])) {
            return $container->privates['App\\Security\\RecaptchaLoginAuthenticator'];
        }

        $instance = new \App\Security\RecaptchaLoginAuthenticator(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $a, ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), $container->getEnv('RECAPTCHA_SECRET_KEY'));

        if (isset($container->privates['App\\Security\\RecaptchaLoginAuthenticator'])) {
            return $container->privates['App\\Security\\RecaptchaLoginAuthenticator'];
        }

        return $container->privates['App\\Security\\RecaptchaLoginAuthenticator'] = $instance;
    }
}
