<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Assets_PackageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.assets.package' shared service.
     *
     * @return \Symfony\Component\Asset\PathPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'admin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Asset'.\DIRECTORY_SEPARATOR.'LastModifiedVersionStrategy.php';

        return $container->privates['sonata.admin.assets.package'] = new \Symfony\Component\Asset\PathPackage('/', new \Sonata\AdminBundle\Asset\LastModifiedVersionStrategy(\dirname(__DIR__, 4), '/public'), ($container->privates['assets.context'] ?? self::getAssets_ContextService($container)));
    }
}
