<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedFullDataCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SeedFullDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\SeedFullDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed-full-data', [], 'Add comprehensive test data (100+ rows)', false, #[\Closure(name: 'App\\Command\\SeedFullDataCommand')] fn (): \App\Command\SeedFullDataCommand => ($container->privates['App\\Command\\SeedFullDataCommand'] ?? $container->load('getSeedFullDataCommandService')));
    }
}
