<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TransportController' shared autowired service.
     *
     * @return \App\Controller\TransportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TransportController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'PaymentService.php';

        $container->services['App\\Controller\\TransportController'] = $instance = new \App\Controller\TransportController(($container->privates['App\\Service\\Api\\PaymentService'] ??= new \App\Service\Api\PaymentService()), ($container->privates['App\\Service\\ReceiptService'] ?? $container->load('getReceiptServiceService')), ($container->privates['App\\Service\\Api\\MailerService'] ?? $container->load('getMailerServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\TransportController', $container));

        return $instance;
    }
}
