<?php

namespace ContainerG2VwSaC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravelPreparationAssistantServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TravelPreparationAssistantService' shared autowired service.
     *
     * @return \App\Service\TravelPreparationAssistantService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TravelPreparationAssistantService.php';

        return $container->privates['App\\Service\\TravelPreparationAssistantService'] = new \App\Service\TravelPreparationAssistantService($container->getEnv('OPENAI_API_KEY'), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
