<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GnEZU85Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.gnEZU85' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hfService' => ['privates', 'App\\Service\\HuggingFaceService', 'getHuggingFaceServiceService', true],
            'openAIService' => ['privates', 'App\\Service\\OpenAIService', 'getOpenAIServiceService', true],
            'repo' => ['privates', 'App\\Repository\\FAQRepository', 'getFAQRepositoryService', true],
        ], [
            'em' => '?',
            'hfService' => 'App\\Service\\HuggingFaceService',
            'openAIService' => 'App\\Service\\OpenAIService',
            'repo' => 'App\\Repository\\FAQRepository',
        ]);

        if (isset($container->privates['.service_locator.gnEZU85'])) {
            return $container->privates['.service_locator.gnEZU85'];
        }

        return $container->privates['.service_locator.gnEZU85'] = $instance;
    }
}
