<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B69q6sUService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.B69q6sU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B69q6sU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actRepo' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'avisRepo' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'bookRepo' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
            'circRepo' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
            'circuitAvisRepo' => ['privates', 'App\\Repository\\CircuitAvisRepository', 'getCircuitAvisRepositoryService', true],
            'commentRepo' => ['privates', 'App\\Repository\\ForumCommentRepository', 'getForumCommentRepositoryService', true],
            'forumRepo' => ['privates', 'App\\Repository\\ForumPostRepository', 'getForumPostRepositoryService', true],
            'hebRepo' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', true],
            'profilRepo' => ['privates', 'App\\Repository\\ProfilVoyageurRepository', 'getProfilVoyageurRepositoryService', true],
            'rcRepo' => ['privates', 'App\\Repository\\ReservationCircuitRepository', 'getReservationCircuitRepositoryService', true],
            'resRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'transportRepo' => ['privates', 'App\\Repository\\TransportOfferRepository', 'getTransportOfferRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'actRepo' => 'App\\Repository\\ActivityRepository',
            'avisRepo' => 'App\\Repository\\AvisRepository',
            'bookRepo' => 'App\\Repository\\BookingRepository',
            'circRepo' => 'App\\Repository\\CircuitRepository',
            'circuitAvisRepo' => 'App\\Repository\\CircuitAvisRepository',
            'commentRepo' => 'App\\Repository\\ForumCommentRepository',
            'forumRepo' => 'App\\Repository\\ForumPostRepository',
            'hebRepo' => 'App\\Repository\\HebergementRepository',
            'profilRepo' => 'App\\Repository\\ProfilVoyageurRepository',
            'rcRepo' => 'App\\Repository\\ReservationCircuitRepository',
            'resRepo' => 'App\\Repository\\ReservationRepository',
            'transportRepo' => 'App\\Repository\\TransportOfferRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
