<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PAJ2wHkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.pAJ2wHk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paymentService' => ['privates', 'App\\Service\\PaymentService', 'getPaymentServiceService', true],
            'repo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'paymentService' => 'App\\Service\\PaymentService',
            'repo' => 'App\\Repository\\ReservationRepository',
        ]);

        if (isset($container->privates['.service_locator.pAJ2wHk'])) {
            return $container->privates['.service_locator.pAJ2wHk'];
        }

        return $container->privates['.service_locator.pAJ2wHk'] = $instance;
    }
}
