<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0IO1L8PService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.0IO1L8P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\CircuitRepository',
        ]);

        if (isset($container->privates['.service_locator.0IO1L8P'])) {
            return $container->privates['.service_locator.0IO1L8P'];
        }

        return $container->privates['.service_locator.0IO1L8P'] = $instance;
    }
}
