<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_22UKUV4Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.22UKUV4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.22UKUV4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'spellChecker' => ['privates', 'App\\Service\\FrenchSpellChecker', 'getFrenchSpellCheckerService', true],
        ], [
            'spellChecker' => 'App\\Service\\FrenchSpellChecker',
        ]);
    }
}
