<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VH_28keService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.vH.28ke' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\FavoriteTransportRepository', 'getFavoriteTransportRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\FavoriteTransportRepository',
        ]);

        if (isset($container->privates['.service_locator.vH.28ke'])) {
            return $container->privates['.service_locator.vH.28ke'];
        }

        return $container->privates['.service_locator.vH.28ke'] = $instance;
    }
}
