<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_341LqXGService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.341LqXG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'faqRepo' => ['privates', 'App\\Repository\\FAQRepository', 'getFAQRepositoryService', true],
        ], [
            'em' => '?',
            'faqRepo' => 'App\\Repository\\FAQRepository',
        ]);

        if (isset($container->privates['.service_locator.341LqXG'])) {
            return $container->privates['.service_locator.341LqXG'];
        }

        return $container->privates['.service_locator.341LqXG'] = $instance;
    }
}
