<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EsALWiCService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.EsALWiC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.EsALWiC.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.EsALWiC": it needs an instance of "App\\Entity\\Booking" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'booking' => 'App\\Entity\\Booking',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.EsALWiC'])) {
            return $container->privates['.service_locator.EsALWiC'];
        }

        return $container->privates['.service_locator.EsALWiC'] = $instance;
    }
}
