<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YX0L07EService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.YX0L07E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\FavoritePostRepository', 'getFavoritePostRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\FavoritePostRepository',
        ]);

        if (isset($container->privates['.service_locator.YX0L07E'])) {
            return $container->privates['.service_locator.YX0L07E'];
        }

        return $container->privates['.service_locator.YX0L07E'] = $instance;
    }
}
