<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mhh6zYoService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.mhh6zYo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\LikeDislikeRepository', 'getLikeDislikeRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\LikeDislikeRepository',
        ]);

        if (isset($container->privates['.service_locator.mhh6zYo'])) {
            return $container->privates['.service_locator.mhh6zYo'];
        }

        return $container->privates['.service_locator.mhh6zYo'] = $instance;
    }
}
