<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W1HPdhQService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.w1HPdhQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'review' => ['privates', '.errored..service_locator.w1HPdhQ.App\\Entity\\Review', NULL, 'Cannot autowire service ".service_locator.w1HPdhQ": it needs an instance of "App\\Entity\\Review" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'review' => 'App\\Entity\\Review',
        ]);

        if (isset($container->privates['.service_locator.w1HPdhQ'])) {
            return $container->privates['.service_locator.w1HPdhQ'];
        }

        return $container->privates['.service_locator.w1HPdhQ'] = $instance;
    }
}
