<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SNB9eHeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.SNB9eHe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avis' => ['privates', '.errored..service_locator.SNB9eHe.App\\Entity\\CircuitAvis', NULL, 'Cannot autowire service ".service_locator.SNB9eHe": it needs an instance of "App\\Entity\\CircuitAvis" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'avis' => 'App\\Entity\\CircuitAvis',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.SNB9eHe'])) {
            return $container->privates['.service_locator.SNB9eHe'];
        }

        return $container->privates['.service_locator.SNB9eHe'] = $instance;
    }
}
