<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Resolver_Factory_ItemSubscriptionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.graphql.resolver.factory.item_subscription' shared service.
     *
     * @return \ApiPlatform\GraphQl\Resolver\Factory\ItemSubscriptionResolverFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ResolverFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'GraphQl'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ItemSubscriptionResolverFactory.php';

        return $container->privates['api_platform.graphql.resolver.factory.item_subscription'] = new \ApiPlatform\GraphQl\Resolver\Factory\ItemSubscriptionResolverFactory(($container->privates['api_platform.graphql.resolver.stage.read'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_ReadService')), ($container->privates['api_platform.graphql.resolver.stage.security'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_SecurityService')), ($container->privates['api_platform.graphql.resolver.stage.serialize'] ?? $container->load('getApiPlatform_Graphql_Resolver_Stage_SerializeService')), ($container->privates['api_platform.graphql.subscription.subscription_manager'] ?? $container->load('getApiPlatform_Graphql_Subscription_SubscriptionManagerService')), ($container->privates['api_platform.graphql.subscription.mercure_iri_generator'] ?? $container->load('getApiPlatform_Graphql_Subscription_MercureIriGeneratorService')));
    }
}
