<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityApiControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\ActivityApiController' shared autowired service.
     *
     * @return \App\Controller\Api\ActivityApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'ActivityApiController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'PlacesApiService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'AiService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'TripAdvisorService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'ViatorService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GetYourGuideService.php';

        $container->services['App\\Controller\\Api\\ActivityApiController'] = $instance = new \App\Controller\Api\ActivityApiController(($container->privates['App\\Repository\\ActivityRepository'] ?? $container->load('getActivityRepositoryService')), ($container->privates['App\\Service\\Api\\ActivityApiService'] ?? $container->load('getActivityApiServiceService')), ($container->privates['App\\Service\\Api\\PlacesApiService'] ??= new \App\Service\Api\PlacesApiService()), ($container->privates['App\\Service\\Api\\AiService'] ??= new \App\Service\Api\AiService()), ($container->privates['App\\Service\\Api\\TripAdvisorService'] ??= new \App\Service\Api\TripAdvisorService()), ($container->privates['App\\Service\\Api\\ViatorService'] ??= new \App\Service\Api\ViatorService()), ($container->privates['App\\Service\\Api\\GetYourGuideService'] ??= new \App\Service\Api\GetYourGuideService()), ($container->privates['App\\Service\\NearbyActivityService'] ?? $container->load('getNearbyActivityServiceService')), ($container->privates['App\\Service\\RecommendationService'] ?? $container->load('getRecommendationServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\ActivityApiController', $container));

        return $instance;
    }
}
