<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircuitAiPlannerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\CircuitAiPlanner' shared autowired service.
     *
     * @return \App\Service\CircuitAiPlanner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CircuitAiPlanner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'MistralService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'SherpaService.php';

        return $container->privates['App\\Service\\CircuitAiPlanner'] = new \App\Service\CircuitAiPlanner(($container->privates['App\\Service\\Api\\MistralService'] ??= new \App\Service\Api\MistralService()), ($container->privates['App\\Service\\Api\\SherpaService'] ??= new \App\Service\Api\SherpaService()));
    }
}
