<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCallServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\CallService' shared autowired service.
     *
     * @return \App\Service\CallService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CallService.php';

        return $container->privates['App\\Service\\CallService'] = new \App\Service\CallService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)));
    }
}
