<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircuitPdfServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\CircuitPdfService' shared autowired service.
     *
     * @return \App\Service\CircuitPdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CircuitPdfService.php';

        return $container->privates['App\\Service\\CircuitPdfService'] = new \App\Service\CircuitPdfService(($container->privates['twig'] ?? self::getTwigService($container)));
    }
}
