<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ChatbotService' shared autowired service.
     *
     * @return \App\Service\ChatbotService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ChatbotService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NLPService.php';

        return $container->privates['App\\Service\\ChatbotService'] = new \App\Service\ChatbotService(($container->privates['App\\Service\\OpenAIService'] ?? $container->load('getOpenAIServiceService')), ($container->privates['App\\Service\\NLPService'] ??= new \App\Service\NLPService()), ($container->privates['App\\Repository\\FAQRepository'] ?? $container->load('getFAQRepositoryService')), ($container->privates['App\\Repository\\CircuitRepository'] ?? $container->load('getCircuitRepositoryService')), ($container->privates['App\\Service\\HuggingFaceService'] ?? $container->load('getHuggingFaceServiceService')), ($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
