<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataTableExporterCollectionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Exporter\DataTableExporterCollection' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\DataTableExporterCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'DataTableExporterCollection.php';

        return $container->privates['Omines\\DataTablesBundle\\Exporter\\DataTableExporterCollection'] = new \Omines\DataTablesBundle\Exporter\DataTableExporterCollection(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter'] ??= new \Omines\DataTablesBundle\Exporter\Excel\ExcelExporter());
            yield 1 => ($container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter'] ??= new \Omines\DataTablesBundle\Exporter\Excel\ExcelOpenSpoutExporter());
            yield 2 => ($container->privates['Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter'] ??= new \Omines\DataTablesBundle\Exporter\Csv\CsvExporter());
        }, 3));
    }
}
