<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatatables_ExporterLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'datatables.exporter_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['datatables.exporter_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter' => ['privates', 'Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter', 'getCsvExporterService', true],
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter' => ['privates', 'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter', 'getExcelExporterService', true],
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter' => ['privates', 'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter', 'getExcelOpenSpoutExporterService', true],
        ], [
            'Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter' => '?',
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter' => '?',
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter' => '?',
        ]);
    }
}
