<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_VarDumper_ClonerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'debug.var_dumper.cloner' shared service.
     *
     * @return \Symfony\Component\VarDumper\Cloner\VarCloner
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['debug.var_dumper.cloner'] = new \Symfony\Component\VarDumper\Cloner\VarCloner();
    }
}
