<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatatables_AdapterLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'datatables.adapter_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['datatables.adapter_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Omines\\DataTablesBundle\\Adapter\\ArrayAdapter' => [false, 'Omines\\DataTablesBundle\\Adapter\\ArrayAdapter', 'getArrayAdapterService', true],
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\FetchJoinORMAdapter' => [false, 'Omines\\DataTablesBundle\\Adapter\\Doctrine\\FetchJoinORMAdapter', 'getFetchJoinORMAdapterService', true],
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter' => [false, 'Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter', 'getORMAdapterService', true],
        ], [
            'Omines\\DataTablesBundle\\Adapter\\ArrayAdapter' => '?',
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\FetchJoinORMAdapter' => '?',
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter' => '?',
        ]);
    }
}
