<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityMetadataProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Metadata\EntityMetadataProvider' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Metadata\EntityMetadataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Metadata'.\DIRECTORY_SEPARATOR.'EntityMetadataProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Metadata\\EntityMetadataProvider'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Metadata\\EntityMetadataProvider'];
        }

        $instance = new \AhmedBhs\DoctrineDoctor\Metadata\EntityMetadataProvider($a, true);

        if (isset($container->privates['AhmedBhs\\DoctrineDoctor\\Metadata\\EntityMetadataProvider'])) {
            return $container->privates['AhmedBhs\\DoctrineDoctor\\Metadata\\EntityMetadataProvider'];
        }

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Metadata\\EntityMetadataProvider'] = $instance;
    }
}
