<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrenchSpellCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\FrenchSpellChecker' shared autowired service.
     *
     * @return \App\Service\FrenchSpellChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FrenchSpellChecker.php';

        return $container->privates['App\\Service\\FrenchSpellChecker'] = new \App\Service\FrenchSpellChecker();
    }
}
