<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\HebergementService' shared autowired service.
     *
     * @return \App\Service\HebergementService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HebergementService.php';

        return $container->services['App\\Service\\HebergementService'] = new \App\Service\HebergementService(($container->privates['App\\Repository\\HebergementRepository'] ?? $container->load('getHebergementRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
