<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstantiatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\DependencyInjection\Instantiator' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\DependencyInjection\Instantiator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'Instantiator.php';

        return $container->privates['Omines\\DataTablesBundle\\DependencyInjection\\Instantiator'] = new \Omines\DataTablesBundle\DependencyInjection\Instantiator(['Omines\\DataTablesBundle\\Adapter\\AdapterInterface' => ($container->privates['datatables.adapter_locator'] ?? $container->load('getDatatables_AdapterLocatorService')), 'Omines\\DataTablesBundle\\Column\\AbstractColumn' => ($container->privates['datatables.column_locator'] ?? $container->load('getDatatables_ColumnLocatorService')), 'Omines\\DataTablesBundle\\DataTableTypeInterface' => ($container->privates['datatables.type_locator'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])), 'Omines\\DataTablesBundle\\Exporter\\DataTableExporterInterface' => ($container->privates['datatables.exporter_locator'] ?? $container->load('getDatatables_ExporterLocatorService'))]);
    }
}
