<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpGaufrette_Command_FilesystemKeysService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'knp_gaufrette.command.filesystem_keys' shared service.
     *
     * @return \Knp\Bundle\GaufretteBundle\Command\FilesystemKeysCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'knp-gaufrette-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FilesystemKeysCommand.php';

        $container->privates['knp_gaufrette.command.filesystem_keys'] = $instance = new \Knp\Bundle\GaufretteBundle\Command\FilesystemKeysCommand(($container->services['knp_gaufrette.filesystem_map'] ?? $container->load('getKnpGaufrette_FilesystemMapService')));

        $instance->setName('gaufrette:filesystem:keys');

        return $instance;
    }
}
