<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\MessageService' shared autowired service.
     *
     * @return \App\Service\MessageService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MessageService.php';

        return $container->privates['App\\Service\\MessageService'] = new \App\Service\MessageService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ConversationRepository'] ?? $container->load('getConversationRepositoryService')), ($container->privates['App\\Repository\\MessageRepository'] ?? $container->load('getMessageRepositoryService')), ($container->privates['App\\Repository\\ConversationParticipantRepository'] ?? $container->load('getConversationParticipantRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
