<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\MailerService' shared autowired service.
     *
     * @return \App\Service\Api\MailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'MailerService.php';

        return $container->privates['App\\Service\\Api\\MailerService'] = new \App\Service\Api\MailerService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
