<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMopaBootstrap_Form_TypeExtension_HelpService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'mopa_bootstrap.form.type_extension.help' shared service.
     *
     * @return \Mopa\Bundle\BootstrapBundle\Form\Extension\HelpFormTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mopa'.\DIRECTORY_SEPARATOR.'bootstrap-bundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'HelpFormTypeExtension.php';

        return $container->privates['mopa_bootstrap.form.type_extension.help'] = new \Mopa\Bundle\BootstrapBundle\Form\Extension\HelpFormTypeExtension(['help_block_tooltip' => $container->parameters['mopa_bootstrap.form.help_block.tooltip'], 'help_block_popover' => $container->parameters['mopa_bootstrap.form.help_block.popover'], 'help_label_tooltip' => $container->parameters['mopa_bootstrap.form.help_label.tooltip'], 'help_label_popover' => $container->parameters['mopa_bootstrap.form.help_label.popover'], 'help_widget_popover' => $container->parameters['mopa_bootstrap.form.help_widget.popover']]);
    }
}
