<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissingIndexAnalyzerConfigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Performance\MissingIndexAnalyzerConfig' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Performance\MissingIndexAnalyzerConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Performance'.\DIRECTORY_SEPARATOR.'MissingIndexAnalyzerConfig.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Performance\\MissingIndexAnalyzerConfig'] = new \AhmedBhs\DoctrineDoctor\Analyzer\Performance\MissingIndexAnalyzerConfig(50, 1000, 10, true);
    }
}
