<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMopaBootstrap_Form_TypeExtension_TabbedService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'mopa_bootstrap.form.type_extension.tabbed' shared service.
     *
     * @return \Mopa\Bundle\BootstrapBundle\Form\Extension\TabbedFormTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mopa'.\DIRECTORY_SEPARATOR.'bootstrap-bundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'TabbedFormTypeExtension.php';

        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->privates['mopa_bootstrap.form.type_extension.tabbed'])) {
            return $container->privates['mopa_bootstrap.form.type_extension.tabbed'];
        }

        $instance = new \Mopa\Bundle\BootstrapBundle\Form\Extension\TabbedFormTypeExtension($a, ['class' => 'nav nav-tabs']);

        if (isset($container->privates['mopa_bootstrap.form.type_extension.tabbed'])) {
            return $container->privates['mopa_bootstrap.form.type_extension.tabbed'];
        }

        return $container->privates['mopa_bootstrap.form.type_extension.tabbed'] = $instance;
    }
}
