<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenRouterServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\OpenRouterService' shared autowired service.
     *
     * @return \App\Service\OpenRouterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OpenRouterService.php';

        return $container->privates['App\\Service\\OpenRouterService'] = new \App\Service\OpenRouterService($container->getEnv('OPENROUTER_API_KEY'), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
