<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOneupFlysystem_ActivityAdapterAdapterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'oneup_flysystem.activity_adapter_adapter' shared service.
     *
     * @return \League\Flysystem\Local\LocalFilesystemAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['oneup_flysystem.activity_adapter_adapter'] = $container->createProxy('LocalFilesystemAdapterGhost3634d74', static fn () => \LocalFilesystemAdapterGhost3634d74::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FilesystemAdapter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ChecksumProvider.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem-local'.\DIRECTORY_SEPARATOR.'LocalFilesystemAdapter.php';

        return ($lazyLoad->__construct((\dirname(__DIR__, 4).'/public/uploads/activities'), NULL, 2, 2, NULL, false) && false ?: $lazyLoad);
    }
}
