<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilVoyageurService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Iyq7osO.App\Entity\ProfilVoyageur' shared service.
     *
     * @return \App\Entity\ProfilVoyageur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Iyq7osO": it needs an instance of "App\\Entity\\ProfilVoyageur" but this type has been excluded in "config/services.yaml".');
    }
}
