<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReceiptServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ReceiptService' shared autowired service.
     *
     * @return \App\Service\ReceiptService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ReceiptService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'QrCodeService.php';

        return $container->privates['App\\Service\\ReceiptService'] = new \App\Service\ReceiptService(($container->privates['App\\Service\\Api\\QrCodeService'] ??= new \App\Service\Api\QrCodeService()));
    }
}
