<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4mcuqxd.App\Entity\Story' shared service.
     *
     * @return \App\Entity\Story
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4mcuqxd": it needs an instance of "App\\Entity\\Story" but this type has been excluded in "config/services.yaml".');
    }
}
