<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSqlStructureExtractorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\Analyzer\Parser\SqlStructureExtractor' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\Analyzer\Parser\CachedSqlStructureExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'SqlStructureExtractor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Analyzer'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'CachedSqlStructureExtractor.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\Analyzer\\Parser\\SqlStructureExtractor'] = new \AhmedBhs\DoctrineDoctor\Analyzer\Parser\CachedSqlStructureExtractor();
    }
}
