<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoryApiControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\StoryApiController' shared autowired service.
     *
     * @return \App\Controller\Api\StoryApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'StoryApiController.php';

        $container->services['App\\Controller\\Api\\StoryApiController'] = $instance = new \App\Controller\Api\StoryApiController(($container->privates['App\\Service\\StoryService'] ?? $container->load('getStoryServiceService')), ($container->privates['App\\Repository\\StoryRepository'] ?? $container->load('getStoryRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\StoryApiController', $container));

        return $instance;
    }
}
