<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwigRendererService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Twig\TwigRenderer' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Twig\TwigRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataTableRendererInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'TwigRenderer.php';

        return $container->privates['Omines\\DataTablesBundle\\Twig\\TwigRenderer'] = new \Omines\DataTablesBundle\Twig\TwigRenderer(($container->privates['twig'] ?? self::getTwigService($container)));
    }
}
