<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkerModeResetSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AhmedBhs\DoctrineDoctor\EventSubscriber\WorkerModeResetSubscriber' shared autowired service.
     *
     * @return \AhmedBhs\DoctrineDoctor\EventSubscriber\WorkerModeResetSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ahmed-bhs'.\DIRECTORY_SEPARATOR.'doctrine-doctor'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'WorkerModeResetSubscriber.php';

        return $container->privates['AhmedBhs\\DoctrineDoctor\\EventSubscriber\\WorkerModeResetSubscriber'] = new \AhmedBhs\DoctrineDoctor\EventSubscriber\WorkerModeResetSubscriber();
    }
}
