<?php

namespace ContainerUGQUFTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getYelpServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\YelpService' shared autowired service.
     *
     * @return \App\Service\Api\YelpService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'YelpService.php';

        return $container->privates['App\\Service\\Api\\YelpService'] = new \App\Service\Api\YelpService($container->getEnv('default::YELP_API_KEY'));
    }
}
