<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG2VwSaC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG2VwSaC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG2VwSaC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG2VwSaC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG2VwSaC\App_KernelDevDebugContainer([
    'container.build_hash' => 'G2VwSaC',
    'container.build_id' => '29aee73f',
    'container.build_time' => 1777754456,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG2VwSaC');
